'use strict';
(() => {
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const key='nutrideck.cardgym.v1';
const presets={editorial:{name:'Éditorial',sub:'Précis, clair, essentiel',accent:'#336648',paper:'#fffdf3',ink:'#202a26',radius:13,font:1,photo:1,shadow:28},arena:{name:'Arène',sub:'Collection et contraste',accent:'#c4f073',paper:'#1e2c28',ink:'#f1f4e9',radius:14,font:1,photo:1,shadow:40},studio:{name:'Studio',sub:'Chaleureux et illustré',accent:'#a1462e',paper:'#fff3db',ink:'#422a20',radius:19,font:1,photo:1,shadow:20}};
const defaults=()=>({v:1,design:'editorial',...presets.editorial,ratio:1.4,size:190,metric:'sugars',fields:{brand:true,qty:true,nutri:true,nova:true,eco:false,metric:true}});
const bounds={ratio:[1.25,1.55],size:[140,300],radius:[0,30],font:[.85,1.25],photo:[.7,1.35],shadow:[0,60]};
function validate(x){if(!x||typeof x!=='object'||x.v!==1)throw Error('Format de style non reconnu.');const d=defaults();if(!Object.hasOwn(presets,x.design))throw Error('Direction inconnue.');d.design=x.design;for(const k of ['accent','paper','ink']){if(typeof x[k]!=='string'||!/^#[a-f\d]{6}$/i.test(x[k]))throw Error('Couleur invalide.');d[k]=x[k];}for(const [k,[lo,hi]]of Object.entries(bounds)){if(!Number.isFinite(x[k])||x[k]<lo||x[k]>hi)throw Error('Valeur hors limites : '+k);d[k]=x[k];}if(!['sugars','kcal','prot','salt','fiber'].includes(x.metric))throw Error('Statistique inconnue.');d.metric=x.metric;for(const k of Object.keys(d.fields)){if(typeof x.fields?.[k]!=='boolean')throw Error('Champ invalide.');d.fields[k]=x.fields[k];}return d;}
let cfg=defaults(),pinned=null;try{const old=JSON.parse(localStorage.getItem(key));if(old)cfg=validate(old);}catch{}
let view='solo',face='front',stress='normal',help=false,current=0;
const stats={sugars:['Sucres','g'],kcal:['Énergie','kcal'],prot:['Protéines','g'],salt:['Sel','g'],fiber:['Fibres','g'],fat:['Lipides','g'],sat:['Saturés','g']};
let products=[{code:'demo-avoine',name:'Flocons d’avoine',brand:'Exemple de mise en page',qty:'500 g',img:'',nutri:'a',nova:1,eco:'b',n:{sugars:1.1,kcal:372,prot:13,salt:.01,fiber:10,fat:7,sat:1.3},ingredients:'Avoine. Données de démonstration reprises du prototype.',allergens:[],demo:true}];
const fmt=v=>v===null||v===undefined||!Number.isFinite(Number(v))?'—':Number(v).toLocaleString('fr-CA',{maximumFractionDigits:2});
const grade=g=>/^[a-e]$/i.test(g||'')?g.toUpperCase():'—';
function save(){try{localStorage.setItem(key,JSON.stringify(cfg));}catch{notice('Sauvegarde locale indisponible. Exporte ton style.');}}
let noticeTimer;function notice(text){$('#notice').textContent=text;$('#notice').style.display='block';clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>$('#notice').style.display='none',3200);}
function product(){const p=structuredClone(products[current]||products[0]);if(stress==='long')p.name='Granola croustillant aux amandes, chocolat noir et petits fruits du Québec';if(stress==='noimage')p.img='';if(stress==='missing'){p.n={};p.nutri=null;p.eco=null;p.nova=null;p.ingredients='';}return p;}
function safeImage(url){if(!url)return '';try{const u=new URL(url,location.href);return ['http:','https:'].includes(u.protocol)?u.href:'';}catch{return '';}}
function makeCard(p,cfg,{width=290,face='front',design=cfg.design,click}={}){
 const d=document.createElement('article');d.className='nd-card';d.dataset.design=design;d.tabIndex=0;d.setAttribute('role','button');d.setAttribute('aria-label',face==='mystery'?'Carte mystère':p.name+' — '+(face==='back'?'verso':'recto')+'. Cliquer pour retourner.');
 const color={A:'#23724a',B:'#577f1b',C:'#846b00',D:'#ae5a16',E:'#b8392c'}[grade(p.nutri)]||'#667365';
 // Identity, content and score-dependent color are all absent on the mystery face.
 for(const[k,v]of Object.entries({'--width':width+'px','--ratio':cfg.ratio,'--radius':cfg.radius+'px','--font':cfg.font,'--image-scale':cfg.photo,'--shadow':cfg.shadow/100,'--paper':cfg.paper,'--ink':cfg.ink,'--accent':cfg.accent,'--grade':face==='mystery'?'#667365':color}))d.style.setProperty(k,v);
 if(face==='mystery')d.innerHTML='<div class="nd-face nd-mystery"><span class="seal">N</span><b>NutriDeck</b><small>À VOUS DE JOUER</small></div>';
 else if(face==='back')d.innerHTML=`<div class="nd-face nd-back"><div class="nd-overline">LA FICHE PRODUIT</div><h3 class="nd-title">${esc(p.name)}</h3><div class="nd-table">${Object.entries(stats).map(([k,[name,u]])=>`<div class="nd-row"><span>${name}</span><b>${fmt(p.n?.[k])}${p.n?.[k]!=null?' '+u:''}</b></div>`).join('')}</div><div class="nd-foot">Pour 100 g / 100 ml · selon la source</div><div class="nd-detail"><p><b>Ingrédients</b><br>${esc(p.ingredients||'Non renseignés')}</p><p><b>Allergènes déclarés</b><br>${esc(p.allergens?.length?p.allergens.join(', '):'Non renseignés')}</p></div><div class="nd-source">${p.demo?'DÉMONSTRATION':`OPEN FOOD FACTS · ${esc(p.code)}`}</div></div>`;
 else {const f=cfg.fields,m=stats[cfg.metric],n=p.n?.[cfg.metric],img=safeImage(p.img);
 d.innerHTML=`<div class="nd-face"><div class="nd-top"><span class="nd-brand">${f.brand?esc(p.brand||'Marque non renseignée'):'NUTRIDECK'}</span><span class="nd-id">${esc(p.code?.slice(-3)||'001')}</span></div><h3 class="nd-title" title="${esc(p.name)}">${esc(p.name)}</h3><div class="nd-photo">${img?`<img src="${esc(img)}" alt="${esc(p.name)}" draggable="false">`:'<div class="nd-placeholder"><span>▧</span>Photo non disponible</div>'}${f.qty?`<span class="nd-qty">${esc(p.qty||'Quantité inconnue')}</span>`:''}</div><div class="nd-data">${f.metric?`<div class="nd-metric"><span>${m[0]}</span><b>${fmt(n)}${n!=null?`<em>${m[1]}</em>`:''}</b></div>`:''}<div class="nd-scores">${f.nutri?`<span class="nd-score grade">Nutri<b>${grade(p.nutri)}</b></span>`:''}${f.nova?`<span class="nd-score">NOVA<b>${p.nova||'—'}</b></span>`:''}${f.eco?`<span class="nd-score">Éco<b>${grade(p.eco)}</b></span>`:''}</div><div class="nd-foot">${p.demo?'Données de démonstration':'Pour 100 g / 100 ml'}</div></div></div>`;
 const image=d.querySelector('img');if(image)image.onerror=()=>{image.replaceWith(Object.assign(document.createElement('div'),{className:'nd-placeholder',textContent:'Photo non disponible'}));};}
 d.addEventListener('click',()=>click?.(d));d.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();d.click();}});return d;
}
function wrap(p,c,width,label,options={}){const w=document.createElement('div');w.className='card-wrap';if(label){const l=document.createElement('div');l.className='card-label';l.textContent=label;w.append(l);}w.append(makeCard(p,c,{width,face,...options,click:()=>{if(view==='hand'||view==='grid'){w.querySelector('.nd-card').classList.toggle('selected');}else{face=face==='front'?'back':'front';render();}}}));const sub=document.createElement('div');sub.className='card-sub';sub.textContent=width+' px · '+(face==='mystery'?'Dos neutre':face==='back'?'Verso':'Recto');w.append(sub);return w;}
function render(){const s=$('#stage');s.replaceChildren();s.dataset.view=view;const p=product();
 document.querySelectorAll('[data-view]').forEach(b=>b.tagName==='BUTTON'&&b.setAttribute('aria-pressed',b.dataset.view===view));document.querySelectorAll('[data-face]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.face===face));
 if(view==='solo'){const w=wrap(p,cfg,Math.min(310,window.innerWidth-60),'APERÇU DE TRAVAIL');if(help){const guide=document.createElement('p');guide.className='guide-label';guide.textContent='① Identité stable en haut\n② Photo contenue, sans découpe\n③ Une valeur prioritaire\nCliquer sur la carte pour la retourner.';guide.style.whiteSpace='pre-line';w.append(guide);}s.append(w);if(window.innerWidth>850)s.append(wrap(p,cfg,cfg.size,'TAILLE EN JEU'));}
 if(view==='compare'){if(pinned)s.append(wrap(p,pinned,260,'STYLE ÉPINGLÉ'));for(const [id,pre]of Object.entries(presets)){const c=id===cfg.design?cfg:{...cfg,...pre,design:id};s.append(wrap(p,c,260,pre.name));}}
 if(view==='hand'||view==='grid'){const target=view==='hand'?Object.assign(document.createElement('div'),{className:'hand'}):s;for(let i=0;i<5;i++){const card=wrap(stress==='normal'?products[(current+i)%products.length]:p,cfg,cfg.size,'');card.style.setProperty('--angle',(i-2)*5+'deg');card.style.setProperty('--lift',Math.abs(i-2)*10+'px');target.append(card);}if(view==='hand')s.append(target);}
 $('#caption').textContent={solo:'Cliquer pour retourner · réglages en direct',compare:'Même produit, mêmes données. Comparons la hiérarchie.',hand:'Survole ou touche une carte pour la sélectionner.',grid:'Teste la reconnaissance et la lecture sur une table.'}[view];$('#size-out').textContent=cfg.size+' px';checks();}
function luminance(hex){const a=hex.match(/\w\w/g).map(x=>parseInt(x,16)/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4);return a[0]*.2126+a[1]*.7152+a[2]*.0722;}
function checks(){const a=luminance(cfg.paper.slice(1)),b=luminance(cfg.ink.slice(1));const contrast=(Math.max(a,b)+.05)/(Math.min(a,b)+.05);const small=cfg.size*.035*cfg.font;const rows=[[contrast>=4.5,`Contraste principal ${contrast.toFixed(1)}:1`],[small>=10,`Libellés en jeu ≈ ${small.toFixed(1)} px`],[true,'Mystère : aucune donnée visible']];$('#checks').innerHTML=rows.map(([ok,s])=>`<span class="${ok?'ok':'warn'}">${ok?'✓':'△'} ${s}</span>`).join('');}
function sync(){for(const id of ['ratio','metric','size','accent','paper','ink'])$('#'+id).value=cfg[id];for(const k of ['radius','font','photo','shadow']){const i=$('#'+k);i.value=cfg[k];i.previousElementSibling.textContent=k==='font'||k==='photo'?Math.round(cfg[k]*100)+' %':cfg[k]+(k==='radius'?' px':' %');}for(const k of Object.keys(cfg.fields))$('#field-'+k).checked=cfg.fields[k];document.querySelectorAll('.design').forEach(b=>{b.classList.toggle('on',b.dataset.design===cfg.design);b.setAttribute('aria-pressed',b.dataset.design===cfg.design);});render();}
$('#designs').innerHTML=Object.entries(presets).map(([id,p])=>`<button class="design" data-design="${id}"><span class="swatch" style="background:${p.paper};border-top:8px solid ${p.accent}"></span><span><b>${p.name}</b><small>${p.sub}</small></span></button>`).join('');
$('#designs').onclick=e=>{const b=e.target.closest('button');if(!b)return;cfg={...cfg,...presets[b.dataset.design],design:b.dataset.design};save();sync();};
$('#sliders').innerHTML=[['radius','Angles',0,30,1],['font','Typographie',.85,1.25,.05],['photo','Échelle de la photo',.7,1.35,.05],['shadow','Ombre',0,60,5]].map(([id,l,min,max,step])=>`<label>${l}<output></output><input id="${id}" type="range" min="${min}" max="${max}" step="${step}"></label>`).join('');
$('#fields').innerHTML=Object.entries({brand:'Marque',qty:'Quantité',metric:'Valeur forte',nutri:'Nutri-Score',nova:'NOVA',eco:'Éco-Score'}).map(([id,l])=>`<label><input type="checkbox" id="field-${id}">${l}</label>`).join('');
for(const k of ['ratio','metric','size','accent','paper','ink','radius','font','photo','shadow'])$('#'+k).addEventListener('input',e=>{cfg[k]=Object.hasOwn(bounds,k)?Number(e.target.value):e.target.value;save();sync();});
for(const k of Object.keys(cfg.fields))$('#field-'+k).onchange=e=>{cfg.fields[k]=e.target.checked;save();render();};
$('#views').onclick=e=>{if(e.target.dataset.view){view=e.target.dataset.view;render();}};$('#faces').onclick=e=>{if(e.target.dataset.face){face=e.target.dataset.face;render();}};$('#stress').onchange=e=>{stress=e.target.value;render();};$('#help').onclick=()=>{help=!help;$('#help').setAttribute('aria-pressed',help);render();};$('#pin').onclick=()=>{pinned=structuredClone(cfg);view='compare';render();notice('Style épinglé pour cette session.');};
$('#reset').onclick=()=>{cfg={...defaults(),...presets[cfg.design],design:cfg.design};save();sync();notice('Style réinitialisé.');};
$('#export').onclick=()=>{const blob=new Blob([JSON.stringify(validate(cfg),null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='nutrideck-style-'+cfg.design+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);};$('#import').onclick=()=>$('#file').click();$('#file').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>50000)throw Error('Fichier trop volumineux.');cfg=validate(JSON.parse(await file.text()));save();sync();notice('Style importé.');}catch(err){notice(err.message||'Fichier invalide.');}e.target.value='';};
function updateProducts(){const s=$('#product');s.replaceChildren(...products.map((p,i)=>new Option(p.name+(p.demo?' · démo':''),i)));s.value=current;render();}$('#product').onchange=e=>{current=Number(e.target.value);render();};
function normalize(p){const n=p.nutriments||{};return{code:p.code,name:p.product_name_fr||p.product_name||'Produit sans nom',brand:p.brands||'',qty:p.quantity||'',img:p.localImage||p.image_front_url||'',nutri:p.nutriscore_grade,nova:p.nova_group,eco:p.ecoscore_grade,n:{sugars:n.sugars_100g,kcal:n['energy-kcal_100g'],prot:n.proteins_100g,salt:n.salt_100g,fiber:n.fiber_100g,fat:n.fat_100g,sat:n['saturated-fat_100g']},ingredients:p.ingredients_text_fr||p.ingredients_text||'',allergens:(p.allergens_tags||[]).map(x=>x.replace(/^\w\w:/,''))};}
sync();updateProducts();fetch('gym-products.json').then(r=>{if(!r.ok)throw Error();return r.json();}).then(data=>{const real=data.map(normalize);let saved=[];try{saved=Object.values(JSON.parse(localStorage.getItem('nutrideck.v1'))?.products||{}).filter(p=>p.name&&p.n);}catch{}products=[...real,...saved.filter(p=>!real.some(r=>r.code===p.code)),...products];updateProducts();}).catch(()=>notice('Exemples hors ligne affichés.'));
window.NutriCardGym={makeCard,validate,getStyle:()=>structuredClone(cfg)};
if(document.modelContext?.registerTool){
 const life=new AbortController();
 const tool={name:'configure_card_style',description:'Choisir une direction visuelle du gym et retourner le style actif.',inputSchema:{type:'object',properties:{design:{type:'string',enum:Object.keys(presets)}},required:['design'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||!Object.hasOwn(presets,input.design))throw Error('Direction inconnue');cfg={...cfg,...presets[input.design],design:input.design};save();sync();return{style:structuredClone(cfg)};}};
 try{Promise.resolve(document.modelContext.registerTool(tool,{signal:life.signal})).catch(()=>{});}catch{}
 window.addEventListener('pagehide',()=>life.abort(),{once:true});
}
})();
