(() => {
'use strict';
const $ = s => document.querySelector(s), stage = $('#stage'), dock = $('#action-dock');
const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const names = ['Toi','Léa','Malik','Jo','Charlie','Kim'], colors = ['#ee8635','#a783bc','#73a08a','#ba795f','#819ab7','#b29d58'];
const grades = ['A','B','C','D','E'], gradeColors = ['#439970','#8caa52','#dbb348','#d18a43','#b95945'];
let products = [], cfg = {mode:'nutri', count:4, order:'me-last', tempo:1200, auto:true}, s, timer, due=0, remaining=0, paused=false, sound=false, audio, resumeAfterDialog=false, epoch=0;
const fmt = n => Number(n).toLocaleString('fr-FR',{maximumFractionDigits:1});
const title = p => p.product_name_fr || p.product_name || 'Produit';
const truth = () => cfg.mode === 'nutri' ? s.product.nutriscore_grade.toUpperCase() : Number(s.product.nutriments.sugars_100g);
const value = v => cfg.mode === 'nutri' ? esc(v) : `${fmt(v)} <small>g</small>`;
const avatar = i => `<span class="avatar" style="--avatar:${colors[i]}">${names[i].slice(0,1)}</span>`;
const eligible = mode => products.filter(p => mode === 'nutri' ? /^[a-e]$/i.test(p.nutriscore_grade || '') : Number.isFinite(Number(p.nutriments?.sugars_100g)) && p.nutriments?.sugars_100g !== undefined);
function cancel(){clearTimeout(timer);timer=null;remaining=0;epoch++;}
function announce(text){$('#announcement').textContent=text;}
function tone(f=440){if(!sound)return;try{audio ||= new (window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.connect(g);g.connect(audio.destination);o.frequency.value=f;g.gain.setValueAtTime(.035,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.18);o.start();o.stop(audio.currentTime+.2);}catch{}}
function schedule(ms){clearTimeout(timer); remaining=ms; due=performance.now()+ms;if(paused || (!cfg.auto && s.phase!=='waiting'))return;timer=setTimeout(()=>{timer=null;remaining=0;advance();},ms);}
function start(product, keep=false){cancel();paused=false;const scores=keep?s.total.slice():Array(cfg.count).fill(0),round=keep?s.round+1:1;s={product,round,phase:'vote',choice:null,votes:[],ready:0,index:0,order:[],base:scores,total:scores.slice(),awards:[],shown:[],scored:[]};render();}
function prepare(){if(s.votes.length)return;const t=truth();s.votes=names.slice(0,cfg.count).map((_,i)=>i===0?s.choice:cfg.mode==='nutri'?grades[Math.max(0,Math.min(4,grades.indexOf(t)+[-2,-1,0,0,1,2][Math.floor(Math.random()*6)]))]:Math.round(Math.max(0,Math.min(100,t+(Math.random()-.5)*30))*10)/10);s.order=Array.from({length:cfg.count},(_,i)=>i);if(cfg.order==='me-last')s.order.push(s.order.shift());if(cfg.order==='random')for(let i=s.order.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[s.order[i],s.order[j]]=[s.order[j],s.order[i]];}s.awards=s.votes.map(v=>cfg.mode==='nutri'?([1000,600,250][Math.abs(grades.indexOf(v)-grades.indexOf(t))]||0):Math.max(0,1000-Math.round(Math.abs(v-t)*40)));s.total=s.base.map((b,i)=>b+s.awards[i]);}
function lock(){if(s.phase!=='vote'||s.choice===null)return;prepare();s.phase='waiting';s.ready=1;render();tone();schedule(500);}
function enter(phase,index=0){cancel();s.phase=phase;s.index=index;if(phase==='votes'){const id=s.order[index];if(!s.shown.includes(id))s.shown.push(id);tone(360+index*90);}if(phase==='points'){const id=s.order[index];if(!s.scored.includes(id))s.scored.push(id);tone(500+index*100);}if(phase==='answer')tone(880);render();if(!['vote','final'].includes(phase))schedule(cfg.tempo*(phase==='answer'?1.8:1));}
function advance(){if(!s)return;if(s.phase==='waiting'){s.ready++;if(s.ready>=cfg.count)enter('votes');else{render();schedule(500);}return;}if(s.phase==='votes'){if(s.index+1<cfg.count)enter('votes',s.index+1);else enter('answer');}else if(s.phase==='answer')enter('points');else if(s.phase==='points'){if(s.index+1<cfg.count)enter('points',s.index+1);else enter('final');}}
function mini(){return `<div class="product-mini"><img src="${esc(s.product.localImage)}" alt=""><span>${esc(title(s.product))}</span></div>`;}
function burst(){return `<div class="burst" aria-hidden="true">${Array.from({length:14},(_,i)=>`<i style="--dx:${Math.cos(i*2.4)*155}px;--dy:${Math.sin(i*2.4)*120}px;--spin:${i*51}deg;--piece:${i%2?'#ff9a42':'#ffdb92'}"></i>`).join('')}</div>`;}
function renderPlayers(){ $('#ready-count').textContent=`${s.ready} / ${cfg.count}`;$('#players').innerHTML=names.slice(0,cfg.count).map((n,i)=>{const show=s.shown.includes(i)||['answer','points','final'].includes(s.phase),scored=s.scored.includes(i)||s.phase==='final',active=['votes','points'].includes(s.phase)&&s.order[s.index]===i;return `<div class="player-row ${active?'active-player':''} ${scored?'score-done':''}">${avatar(i)}<div class="player-info"><strong>${n}</strong><small>${i===0?'Ton vote': 'Simulation'} · ${s.phase==='vote'?'réfléchit':i<s.ready?'a voté':'réfléchit'}</small></div>${show?`<span class="vote-chip revealed ${cfg.mode==='sugars'?'numeric':''}">${value(s.votes[i])}</span>`:''}<span class="player-points">${fmt(scored?s.total[i]:s.base[i])}<small>pts</small></span></div>`;}).join('');}
function render(){
const phase=s.phase==='waiting'?'vote':s.phase, phases=['vote','votes','answer','points','final'];document.querySelectorAll('.timeline li').forEach(el=>{el.classList.toggle('active',el.dataset.phase===phase);el.classList.toggle('done',phases.indexOf(el.dataset.phase)<phases.indexOf(phase));if(el.dataset.phase===phase)el.setAttribute('aria-current','step');else el.removeAttribute('aria-current');});
$('#round-number').textContent=String(s.round).padStart(2,'0');$('#simulation-label').textContent=`${cfg.count} joueurs · simulation`;$('#rules-text').textContent=cfg.mode==='nutri'?'Bonne lettre : 1 000 points. Une lettre d’écart : 600. Deux lettres : 250. Au-delà : 0.':'1 000 points au départ, moins 40 points par gramme d’écart. Minimum : 0.';
if(s.phase==='vote'){
stage.innerHTML=`<p class="question-kicker">À TOI DE JOUER</p><h1 class="question-title">${cfg.mode==='nutri'?'Tu lui donnes quelle lettre ?':'Combien de sucres, à ton avis ?'}</h1><p class="question-sub">${cfg.mode==='nutri'?'Devine le Nutri-Score de ce produit.':'Estime la quantité pour 100 g / 100 ml.'}</p><article class="product-card"><span class="product-brand">${esc(s.product.brands)}</span><h2>${esc(title(s.product))}</h2><div class="product-picture"><img src="${esc(s.product.localImage)}" alt="${esc(title(s.product))}"></div><div class="card-footer"><span>PRODUIT À DÉCODER</span><b>NUTRIDECK</b></div><span class="question-chip">?</span></article><div class="ballot"><div class="ballot-label">Ton intuition<small>Le choix reste secret.</small></div>${cfg.mode==='nutri'?`<div class="grade-options" role="group" aria-label="Choisir un Nutri-Score">${grades.map((g,i)=>`<button class="grade-option" data-grade="${g}" aria-pressed="${s.choice===g}" style="--grade:${gradeColors[i]}">${g}</button>`).join('')}</div>`:`<div class="numeric-ballot"><div class="number-controls"><button data-adjust="-1" aria-label="Retirer un gramme">−</button><label class="number-field"><input id="guess-number" type="number" min="0" max="100" step="0.1" inputmode="decimal" aria-label="Estimation en grammes" value="${s.choice??20}"><span>g</span></label><button data-adjust="1" aria-label="Ajouter un gramme">+</button></div><input class="sugar-range" id="guess-range" type="range" min="0" max="100" step="0.1" value="${s.choice??20}" aria-label="Estimation en grammes"><div class="range-labels"><span>0 g</span><span>100 g</span></div></div>`}</div>`;
dock.innerHTML=`<button class="primary-button" data-action="lock" ${s.choice===null?'disabled':''}>Verrouiller mon vote</button><p class="dock-hint">${cfg.mode==='nutri'?'Choisis une lettre pour entrer dans la partie.':'Ajuste la valeur pour confirmer ton estimation.'}</p>`;
}else if(s.phase==='waiting'){
stage.innerHTML=`${mini()}<div class="waiting-orbit">${names.slice(0,cfg.count).map((_,i)=>`<div class="${i<s.ready?'ready':'pending'}">${avatar(i)}</div>`).join('')}</div><div class="locked-choice"><span>TON VOTE EST VERROUILLÉ</span><b>${value(s.choice)}</b></div><h1 class="waiting-title">La table se décide…</h1><p class="waiting-text">${s.ready} vote${s.ready>1?'s':''} sur ${cfg.count}. Le suspense monte.</p><div class="dots" aria-hidden="true"><span></span><span></span><span></span></div>`;dock.innerHTML=`<button class="secondary-button" data-action="skip-wait">Tout le monde a voté</button><p class="dock-hint">Arrivée simulée des autres votes.</p>`;
}else if(s.phase==='votes'){
const id=s.order[s.index];stage.innerHTML=`${mini()}<p class="question-kicker">LES VOTES · ${s.index+1} / ${cfg.count}</p><div class="spotlight">${avatar(id)}<h1 class="player-name">${names[id]}</h1><span class="overline">${id===0?'TU AS CHOISI':'A CHOISI'}</span><div class="reveal-tile"><span class="guess-label">${cfg.mode==='nutri'?'NUTRI-SCORE ESTIMÉ':'SUCRES ESTIMÉS'}</span><b class="guess-value ${cfg.mode==='sugars'?'numeric':''}">${value(s.votes[id])}</b><small>${cfg.mode==='nutri'?'L’intuition est posée.':'pour 100 g / 100 ml'}</small></div></div><div class="revealed-strip">${s.shown.map(i=>`<span class="revealed-token"><small>${names[i]}</small><b>${value(s.votes[i])}</b></span>`).join('')}</div>`;playback();announce(`${names[id]} a voté ${s.votes[id]}${cfg.mode==='sugars'?' grammes':''}.`);
}else if(s.phase==='answer'){
stage.innerHTML=`${mini()}<div class="answer-reveal">${burst()}<p class="question-kicker">LE MOMENT DE VÉRITÉ</p><h1 class="question-title">Et la réponse est…</h1><div class="answer-value ${cfg.mode==='sugars'?'numeric':''}">${value(truth())}</div><p class="answer-caption">${cfg.mode==='nutri'?'Nutri-Score du produit':'de sucres pour 100 g / 100 ml'}</p><p class="phase-note">Donnée Open Food Facts · fiche de test enregistrée</p></div>`;playback();announce(`La réponse est ${truth()}.`);
}else if(s.phase==='points'){
const id=s.order[s.index];stage.innerHTML=`${mini()}<p class="question-kicker">LES POINTS · ${s.index+1} / ${cfg.count}</p><div class="spotlight">${avatar(id)}<h1 class="player-name">${names[id]}</h1><div class="points-number">+<span id="score-count">${s.awards[id]}</span><small>POINTS</small></div><p class="result-label">${s.awards[id]===1000?'Dans le mille !':s.awards[id]>=600?'Bien joué, tout près.':s.awards[id]>0?'Quelques points de sauvés.':'On se reprend à la prochaine.'}</p><div class="comparison"><div><small>${id===0?'TON VOTE':'SON VOTE'}</small><b>${value(s.votes[id])}</b></div><div><small>LA RÉPONSE</small><b>${value(truth())}</b></div></div></div>`;playback();countUp(s.awards[id]);announce(`${names[id]} gagne ${s.awards[id]} points.`);
}else{
const rank=Array.from({length:cfg.count},(_,i)=>i).sort((a,b)=>s.total[b]-s.total[a]);stage.innerHTML=`<div class="final-header">${avatar(rank[0])}<p class="eyebrow">MANCHE ${String(s.round).padStart(2,'0')} TERMINÉE</p><h1 class="final-title">${rank[0]===0?'Tu es en tête.':`${names[rank[0]]} prend la tête.`}</h1><p class="question-sub">${s.total[rank[0]]===s.total[rank[1]]?'Égalité au sommet. La suite va compter.':'Une autre manche peut tout changer.'}</p></div><ol class="ranking">${rank.map((id,i)=>`<li style="animation-delay:${i*60}ms"><span class="rank-number">${1+rank.filter(j=>s.total[j]>s.total[id]).length}</span>${avatar(id)}<span class="rank-name">${names[id]}<small>+${fmt(s.awards[id])} cette manche</small></span><b class="rank-total">${fmt(s.total[id])}<small>pts</small></b></li>`).join('')}</ol>`;dock.innerHTML='<button class="primary-button" data-action="new">Prochaine manche</button><button class="secondary-button" data-action="replay">Rejouer le reveal</button>';announce('Manche terminée. Classement affiché.');}
renderPlayers();stage.querySelectorAll('img').forEach(img=>img.onerror=()=>{img.style.visibility='hidden';});fitTitle();
}
function fitTitle(){const h=stage.querySelector('.product-card h2');if(!h)return;let size=parseFloat(getComputedStyle(h).fontSize);while(h.offsetHeight>size*1.08*2+1&&size>8){size-=.5;h.style.fontSize=size+'px';}}
function playback(){dock.innerHTML=`<div class="dock-top"><span class="phase-note">${cfg.auto?(paused?'Lecture en pause':'Une révélation à la fois'):'À ton rythme'}</span><button class="playback-button" data-action="pause" ${!cfg.auto?'hidden':''}>${paused?'▶ Reprendre':'Ⅱ Pause'}</button></div><div class="step-track"><span style="animation-duration:${cfg.tempo*(s.phase==='answer'?1.8:1)}ms;animation-play-state:${paused||!cfg.auto?'paused':'running'}"></span></div><div class="dock-buttons"><button class="primary-button" data-action="next">${s.phase==='votes'&&s.index===cfg.count-1?'La réponse':s.phase==='answer'?'Les points':s.phase==='points'&&s.index===cfg.count-1?'Classement':'Suivant'}</button><button class="secondary-button" data-action="end">Résultat</button></div>`;}
function countUp(total){if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;const token=epoch,start=performance.now();const tick=now=>{if(token!==epoch)return;const el=$('#score-count');if(!el)return;const p=Math.min(1,(now-start)/420);el.textContent=fmt(Math.round(total*(1-(1-p)**3)));if(p<1)requestAnimationFrame(tick);};requestAnimationFrame(tick);}
function setPause(next){paused=next;if(paused){remaining=Math.max(0,due-performance.now());clearTimeout(timer);timer=null;}else if(remaining>0)schedule(remaining);if(['votes','answer','points'].includes(s.phase)){const b=dock.querySelector('[data-action=pause]');if(b)b.textContent=paused?'▶ Reprendre':'Ⅱ Pause';const bar=dock.querySelector('.step-track span');if(bar)bar.style.animationPlayState=paused?'paused':'running';}}
function setChoice(n){s.choice=Math.round(Math.min(100,Math.max(0,n))*10)/10;const range=$('#guess-range'),num=$('#guess-number');if(range)range.value=s.choice;if(num&&document.activeElement!==num)num.value=s.choice;dock.querySelector('[data-action=lock]').disabled=false;}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||!s)return;if(b.dataset.grade&&s.phase==='vote'){s.choice=b.dataset.grade;stage.querySelectorAll('[data-grade]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));dock.querySelector('[data-action=lock]').disabled=false;tone(300+grades.indexOf(s.choice)*60);}if(b.dataset.adjust&&s.phase==='vote')setChoice((s.choice??20)+Number(b.dataset.adjust));switch(b.dataset.action){case'lock':lock();break;case'skip-wait':s.ready=cfg.count;enter('votes');break;case'next':advance();break;case'pause':setPause(!paused);break;case'end':s.shown=s.order.slice();s.scored=s.order.slice();enter('final');break;case'replay':s.shown=[];s.scored=[];paused=false;enter('votes');break;case'new':{const list=eligible(cfg.mode);start(list[(list.indexOf(s.product)+1)%list.length],true);break;}}});
stage.addEventListener('input',e=>{if(!['guess-range','guess-number'].includes(e.target.id))return;const n=Number(e.target.value);if(e.target.value===''||!Number.isFinite(n)||n<0||n>100){s.choice=null;dock.querySelector('[data-action=lock]').disabled=true;return;}setChoice(n);});
function options(mode,code){$('#product-select').innerHTML=eligible(mode).map(p=>`<option value="${esc(p.code)}">${esc(title(p))}</option>`).join('');if(eligible(mode).some(p=>p.code===code))$('#product-select').value=code;}
$('#settings-open').onclick=()=>{if(!s)return;resumeAfterDialog=!paused;setPause(true);$('#mode').value=cfg.mode;$('#player-count').value=cfg.count;$('#reveal-order').value=cfg.order;$('#tempo').value=cfg.tempo;$('#tempo-value').textContent=fmt(cfg.tempo/1000)+' s';$('#autoplay').checked=cfg.auto;options(cfg.mode,s.product.code);$('#workshop').showModal();};
$('#settings-close').onclick=()=>$('#workshop').close();$('#workshop').addEventListener('close',()=>{if(resumeAfterDialog)setPause(false);resumeAfterDialog=false;});
$('#mode').onchange=e=>options(e.target.value);$('#tempo').oninput=e=>$('#tempo-value').textContent=fmt(Number(e.target.value)/1000)+' s';
$('#settings-form').onsubmit=e=>{e.preventDefault();cfg={mode:$('#mode').value,count:Number($('#player-count').value),order:$('#reveal-order').value,tempo:Number($('#tempo').value),auto:$('#autoplay').checked};resumeAfterDialog=false;$('#workshop').close();start(products.find(p=>p.code===$('#product-select').value)||eligible(cfg.mode)[0]);};
document.querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>{resumeAfterDialog=false;$('#workshop').close();if(s.choice===null)s.choice=cfg.mode==='nutri'?'C':20;prepare();s.ready=cfg.count;s.shown=b.dataset.jump==='votes'?[]:s.order.slice();s.scored=[];paused=false;enter(b.dataset.jump);});
$('#sound').onclick=()=>{sound=!sound;$('#sound').setAttribute('aria-pressed',String(sound));$('#sound').innerHTML=`Son <span>${sound?'on':'off'}</span>`;$('#sound').title=sound?'Désactiver les sons':'Activer les sons';tone();};
document.addEventListener('visibilitychange',()=>{if(document.hidden&&s&&timer)setPause(true);else if(!document.hidden&&s?.phase==='waiting'&&paused)setPause(false);});
async function init(){try{const response=await fetch('gym-products.json');if(!response.ok)throw Error('load');const data=await response.json();products=Array.isArray(data)?data:data.products;if(!Array.isArray(products)||!eligible('nutri').length)throw Error('data');start(eligible('nutri')[0]);}catch{stage.innerHTML='<div class="error-box"><h1>Les cartes ne sont pas arrivées.</h1><p>Recharge le gym pour réessayer.</p><button id="retry">Réessayer</button></div>';$('#retry').onclick=init;}}
if(document.modelContext?.registerTool){
const lifecycle=new AbortController();
try{Promise.resolve(document.modelContext.registerTool({
name:'advance_mechanics_reveal',title:'Avancer le reveal',description:'Avance la simulation visible d’une étape : prochain vote, réponse, points ou classement. Disponible après le verrouillage du vote.',
inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},
execute(input){if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw Error('Aucun paramètre attendu.');if(!s||!['votes','answer','points'].includes(s.phase))throw Error('Verrouille d’abord un vote et attends le premier reveal.');advance();return {phase:s.phase,joueur:['votes','points'].includes(s.phase)?names[s.order[s.index]]:null,manche:s.round};}
},{signal:lifecycle.signal})).catch(()=>{});}catch{}
window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});
}
init();
})();
