// All game transitions are durable and serialized with a D1 room-version CAS.
const AVATARS=['😀','🦊','🐼','🐸','🦁','🐙','🐵','🐯','🐨','🐧','🦄','🐻','🐮','🐷','🐹','🐰','🤖','🧓','🧢'];
const COUNTRIES={canada:'Canada',france:'France',belgium:'Belgique',switzerland:'Suisse','united-states':'États-Unis','united-kingdom':'Royaume-Uni',germany:'Allemagne',spain:'Espagne',italy:'Italie',portugal:'Portugal',australia:'Australie',world:'Tous les pays'};
const MODE_NAMES={nutri:'Nutri-Score',nova:'NOVA',eco:'Éco-Score'};
const choices=mode=>mode==='nova'?['1','2','3','4']:['A','B','C','D','E'];
const json=(v,status=200)=>Response.json(v,{status,headers:{'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});
function fail(message,status=400){throw Object.assign(new Error(message),{status});}
const db=env=>{if(!env.DB)fail('Le salon est temporairement indisponible.',503);return env.DB;};
const hash=async s=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s))),x=>x.toString(16).padStart(2,'0')).join('');
const rid=()=>crypto.randomUUID().replaceAll('-','');
function profile(b){const name=String(b.name||'').trim().replace(/[\x00-\x1f]/g,'').slice(0,24);if(!name)fail('Choisis ton nom.');if(!AVATARS.includes(b.avatar))fail('Choisis un avatar.');return{name,avatar:b.avatar};}
function options(b){const roulette=b.roulette===true,questionCount=Number(b.questionCount??b.count??7),count=roulette?questionCount:Number(b.count),seconds=Number(b.seconds),novaCount=roulette?0:Number(b.novaCount??0),ecoCount=roulette?0:Number(b.ecoCount??0),readySeconds=Number(b.readySeconds??15),readyEnabled=b.readyEnabled!==false,country=b.country||'canada';if(!Number.isInteger(count)||count<1||count>30||!Number.isInteger(seconds)||seconds<1||seconds>3600||!Number.isInteger(readySeconds)||readySeconds<1||readySeconds>3600||![novaCount,ecoCount].every(n=>Number.isInteger(n)&&n>=0&&n<=5)||!Object.hasOwn(COUNTRIES,country))fail('Choisis de 1 à 30 questions et des durées de 1 à 3 600 secondes.');return{roulette,questionCount:count,count,seconds,novaCount,ecoCount,readySeconds,readyEnabled,country};}
function randomSlot(){const x=new Uint32Array(1);do{crypto.getRandomValues(x);}while(x[0]>=4294967200);return x[0]%100;}
const slotMode=n=>n<85?'nutri':n<95?'eco':'nova';
function enterWheel(s,now){s.phase='wheel';s.step=rid();s.wheelAt=now;s.wheelEndAt=now+4200;s.introEndAt=s.wheelEndAt+3900;s.readyDeadline=null;s.players.forEach(p=>p.ready=false);}
function finishOrNext(s,now){if(s.round+1>=s.schedule.length){s.phase='finished';s.readyDeadline=null;s.lastFinal=snapshot(s);}else{s.round++;enterWheel(s,now);}}
const freshStats=()=>({exact:0,streak:0,bestStreak:0,answered:0,near:0,comebacks:0,optimist:0,pessimist:0,ecoExact:0,novaExact:0,greenExact:0,worst:null});
const schedule=s=>[...Array(s.count).fill('nutri'),...Array(s.novaCount||0).fill('nova'),...Array(s.ecoCount||0).fill('eco')];
const mode=s=>s.schedule?.[s.round]||'nutri';
const answer=s=>mode(s)==='nova'?String(s.deck[s.round].nova_group):String(s.deck[s.round][mode(s)==='eco'?'ecoscore_grade':'nutriscore_grade']).toUpperCase();
function upgrade(s){s.novaCount??=0;s.ecoCount??=0;s.readySeconds??=30;s.country??='world';s.schedule??=schedule(s);s.gameId??='legacy';s.step??='legacy-'+s.round+'-'+s.phase;s.history??=[];s.players.forEach(p=>{p.stats??=freshStats();p.ready??=false;});if(s.phase==='reveal'){s.landAt??=s.lockAt+4300;s.resultAt??=s.lockAt+9000;s.revealPlan??=[{at:900,value:answer(s)},{at:4300,value:answer(s)}];}if(s.phase==='results')s.readyDeadline??=(s.lockAt||s.createdAt)+9000+s.readySeconds*1000;if(s.phase==='finished'&&!s.lastFinal)s.lastFinal=snapshot(s);return s;}
async function read(env,id){const r=await db(env).prepare('SELECT state,version FROM rooms WHERE id=?').bind(id).first();if(!r)fail('Ce salon est introuvable. Vérifie le lien.',404);const s=upgrade(JSON.parse(r.state));s.revision=r.version;return{s,version:r.version};}
function newGate(s,phase,now){s.phase=phase;s.step=rid();s.readyDeadline=now+s.readySeconds*1000;s.players.forEach(p=>p.ready=false);}
function enterVote(s){s.phase='vote';s.step=rid();s.deadline=null;s.readyDeadline=null;s.lockAt=null;s.landAt=null;s.resultAt=null;s.skipped=false;s.players.forEach(p=>{p.ready=false;p.vote=null;p.award=0;p.base=p.score;});}
function nextRound(s,now){const old=mode(s);s.round++;if(mode(s)!==old)newGate(s,'intro',now);else enterVote(s);}
function rollPlan(target,vals,lastStyle){const styles=['direct','reverse','suspense'].filter(x=>x!==lastStyle),style=styles[Math.floor(Math.random()*styles.length)],index=vals.indexOf(target),n=vals.length,cycles=4+Math.floor(Math.random()*3),duration=3200+Math.floor(Math.random()*1100),plan=[];
const end=style==='direct'?index:(index+(style==='reverse'?2:1))%n,steps=cycles*n+end;
for(let i=0;i<=steps;i++){const at=900+Math.round((duration*(style==='direct'?1:.72))*Math.pow(i/steps,1.8));plan.push({at,value:vals[i%n]});}
if(style==='reverse'){plan.push({at:900+Math.round(duration*.84),value:vals[(index+1)%n]},{at:900+duration,value:target});}
if(style==='suspense'){plan.push({at:900+Math.round(duration*.81),value:target},{at:900+Math.round(duration*.91),value:vals[(index+n-1)%n]},{at:900+duration,value:target});}
return{style,plan,duration:duration+900};}
function lock(s,now){s.phase='reveal';s.step=rid();s.lockAt=now;s.deadline=null;s.readyDeadline=null;const correct=answer(s),vals=choices(mode(s)),roll=rollPlan(correct,vals,s.revealStyle);s.revealStyle=roll.style;s.revealPlan=roll.plan;s.landAt=now+roll.duration;s.resultAt=s.landAt+(s.roulette?0:4700);if(s.roulette){s.readyDeadline=s.landAt+s.readySeconds*1000;s.players.forEach(p=>p.ready=false);}
for(const p of s.players){p.base=p.score;const distance=p.vote==null?null:Math.abs(vals.indexOf(p.vote)-vals.indexOf(correct));p.award=s.skipped||distance===null?0:Math.round(([1,.6,.25][distance]||0)*(s.scoreUnit||1000));p.score+=p.award;if(!s.skipped){const st=p.stats;if(distance===1)st.near=(st.near||0)+1;if(distance===0&&st.lastMiss)st.comebacks=(st.comebacks||0)+1;if(distance===0&&mode(s)==='eco')st.ecoExact=(st.ecoExact||0)+1;if(distance===0&&mode(s)==='nova')st.novaExact=(st.novaExact||0)+1;if(distance===0&&correct==='A')st.greenExact=(st.greenExact||0)+1;if(distance>0){const direction=vals.indexOf(p.vote)-vals.indexOf(correct),key=direction<0?'optimist':'pessimist';st[key]=(st[key]||0)+1;}st.lastMiss=distance!==0;st.answered+=distance===null?0:1;st.streak=distance===0?st.streak+1:0;st.bestStreak=Math.max(st.bestStreak,st.streak);if(distance===0)st.exact++;if(distance!==null&&distance>0&&(!st.worst||distance/(vals.length-1)>st.worst.ratio))st.worst={distance,ratio:distance/(vals.length-1),max:vals.length-1,mode:mode(s),guess:p.vote,answer:correct,product:s.deck[s.round].product_name_fr||s.deck[s.round].product_name};}}
s.history.push({round:s.round+1,mode:mode(s),code:s.deck[s.round].code,name:s.deck[s.round].product_name_fr||s.deck[s.round].product_name,answer:correct,skipped:!!s.skipped,insights:insights(s.deck[s.round],mode(s))});}
function snapshot(s){return{gameId:s.gameId,scoreUnit:s.scoreUnit||1000,statsAvailable:s.gameId!=='legacy',country:s.country,total:s.schedule.length,counts:{nutri:s.count,nova:s.novaCount,eco:s.ecoCount},history:s.history,players:s.players.map(p=>({id:p.id,name:p.name,avatar:p.avatar,score:p.score,stats:p.stats}))};}
function advance(s,now){if(s.phase==='loading'&&now-s.loadingAt>35000){s.phase='lobby';s.error='Le chargement a été interrompu. Tu peux réessayer.';}
if(s.phase==='vote'&&s.deadline&&now>=s.deadline)lock(s,s.deadline);
if(s.roulette){
 if(s.phase==='wheel'&&now>=s.wheelEndAt)s.phase='intro';
 if(s.phase==='intro'&&now>=s.introEndAt)enterVote(s);
 if(s.phase==='reveal'&&now>=s.landAt)s.phase='results';
 if(s.phase==='results'&&((s.readyDeadline&&now>=s.readyDeadline)||(s.readyEnabled!==false&&s.players.every(p=>p.ready)&&now>=s.landAt+Math.min(3200,s.readySeconds*1000)))){if(s.round+1>=s.schedule.length)finishOrNext(s,now);else{s.phase='standings';s.step=rid();s.standingsEndAt=now+2600;s.readyDeadline=null;}}
 if(s.phase==='standings'&&now>=s.standingsEndAt)finishOrNext(s,now);
 return;
}
if(s.phase==='reveal'&&now>=s.resultAt){if(s.round+1>=s.schedule.length){s.phase='finished';s.readyDeadline=null;s.lastFinal=snapshot(s);}else newGate(s,'results',now);}
if(['intro','results'].includes(s.phase)&&((s.readyDeadline&&now>=s.readyDeadline)||s.players.every(p=>p.ready))){if(s.phase==='intro')enterVote(s);else nextRound(s,now);}}
async function mutate(env,id,fn){for(let i=0;i<12;i++){const {s,version}=await read(env,id);advance(s,Date.now());await fn(s);s.revision=version+1;const r=await db(env).prepare('UPDATE rooms SET state=?,version=version+1,updated_at=? WHERE id=? AND version=?').bind(JSON.stringify(s),Date.now(),id,version).run();if(r.meta.changes)return s;}fail('La table se synchronise. Réessaie.',409);}
function member(s,token){const p=s.players.find(p=>p.token===token);if(!p)fail('Rejoins le salon avec ton profil.',401);return p;}
function host(s,token){const p=member(s,token);if(p.id!==s.host)fail('Seul l’hôte peut faire cette action.',403);return p;}
function safeProduct(p,landed){if(!p)return null;const o={};for(const k of CARD_FIELDS)if(p[k]!=null)o[k]=p[k];if(!landed){delete o.nutriscore_grade;delete o.nova_group;delete o.ecoscore_grade;}return o;}
function project(s,token){const me=s.players.find(p=>p.token===token),now=Date.now(),locked=['reveal','results','standings','finished'].includes(s.phase),landed=['results','standings','finished'].includes(s.phase)||(s.phase==='reveal'&&now>=s.landAt),current=mode(s);const product=me&&!['wheel','intro','loading','lobby'].includes(s.phase)?safeProduct(s.deck?.[s.round],landed):null;
return{id:s.id,scoreUnit:s.scoreUnit||1000,revision:s.revision||0,phase:s.phase,gameId:s.gameId,step:s.step,host:s.host,me:me?.id||null,roulette:!!s.roulette,questionCount:s.questionCount||s.count,readyEnabled:s.readyEnabled!==false,wheelAt:s.wheelAt||null,wheelEndAt:s.wheelEndAt||null,introEndAt:s.introEndAt||null,wheelSlot:s.roulette&&['wheel','intro'].includes(s.phase)?s.wheelSlots?.[s.round]:null,standingsEndAt:s.standingsEndAt||null,count:s.count,novaCount:s.novaCount,ecoCount:s.ecoCount,country:s.country,seconds:s.seconds,readySeconds:s.readySeconds,round:s.round+1,total:s.schedule.length,requestedTotal:s.requestedTotal||s.schedule.length,mode:current,phaseRound:s.schedule.slice(0,s.round+1).filter(m=>m===current).length,phaseTotal:s.schedule.filter(m=>m===current).length,serverNow:now,deadline:s.deadline||null,readyDeadline:s.readyDeadline||null,lockAt:s.lockAt||null,landAt:s.landAt||null,resultAt:s.resultAt||null,landed,skipped:!!s.skipped,error:s.error||null,source:s.source||null,revealTarget:me&&locked?answer(s):null,revealPlan:me&&locked?s.revealPlan:null,product,insights:me&&landed?insights(s.deck[s.round],current):null,lastFinal:me&&['finished','lobby'].includes(s.phase)?s.lastFinal||null:null,players:s.players.map(p=>({id:p.id,name:p.name,avatar:p.avatar,score:landed||['lobby','intro','wheel'].includes(s.phase)?p.score:(p.base??p.score),base:p.base??p.score,award:landed?p.award||0:0,stats:landed||['lobby','intro','wheel'].includes(s.phase)?p.stats:null,ready:!!p.ready,voted:!!p.vote,vote:me&&(locked||p.id===me.id)?p.vote:null,host:p.id===s.host}))};}
const CARD_FIELDS=['code','product_name','product_name_fr','brands','quantity','image_front_url','nutriscore_grade','nova_group','ecoscore_grade','nutriments','ingredients_text','ingredients_text_fr','allergens_tags','traces_tags','additives_tags','additives_n'];
const fields=[...CARD_FIELDS,'countries_tags','nutrition_grades','nova_groups','nutriscore_version','nutriscore','nutriscore_data','nova_groups_markers','ecoscore_data'];
function normalized(p){const o={};for(const k of fields)if(p[k]!=null)o[k]=p[k];o.code=String(o.code||'');o.brands=Array.isArray(o.brands)?o.brands.join(', '):o.brands||'';o.nutriscore_grade=String(o.nutriscore_grade||o.nutrition_grades||'').toLowerCase();o.nova_group=Number(o.nova_group||o.nova_groups)||null;delete o.nutrition_grades;delete o.nova_groups;
if(o.ecoscore_data){const e=o.ecoscore_data;o.ecoscore_data={grade:e.grade,score:e.score,agribalyse:{score:e.agribalyse?.score,name_fr:e.agribalyse?.name_fr},adjustments:Object.fromEntries(Object.entries(e.adjustments||{}).map(([k,v])=>[k,{value:v.value,warning:v.warning}]))};}
if(o.nutriscore&&o.nutriscore_version)o.nutriscore={[String(o.nutriscore_version)]:o.nutriscore[String(o.nutriscore_version)]};
return o;}
function meaningful(value){return typeof value==='string'&&value.trim().length>1&&!/^(?:non? renseign[ée]s?|unknown|undefined|n\/a|not (?:specified|available)|produit inconnu)$/i.test(value.trim());}
function eligible(p,country,m){const score=m==='nova'?[1,2,3,4].includes(p.nova_group):/^[a-e]$/.test(p[m==='eco'?'ecoscore_grade':'nutriscore_grade']||'');return score&&/^\d{4,24}$/.test(p.code)&&meaningful(p.product_name_fr||p.product_name)&&/^https:\/\/images\.openfoodfacts\.org\//.test(p.image_front_url||'')&&(country==='world'||p.countries_tags?.includes('en:'+country))&&(m!=='nutri'||['energy-kcal_100g','energy-kj_100g','sugars_100g','salt_100g','saturated-fat_100g','proteins_100g'].filter(k=>Number.isFinite(p.nutriments?.[k])).length>=4);}
const shuffle=a=>{for(let i=a.length-1;i>0;i--){const bytes=new Uint32Array(1);crypto.getRandomValues(bytes);const j=bytes[0]%(i+1);[a[i],a[j]]=[a[j],a[i]];}return a;};
async function offJSON(url,timeout=12000,signal){const r=await fetch(url,{headers:{'User-Agent':'NutriDeckGym/0.7 (https://github.com/jutrasimon/nutrideck)','Accept':'application/json'},signal:signal?AbortSignal.any([signal,AbortSignal.timeout(timeout)]):AbortSignal.timeout(timeout)});if(!r.ok||!r.headers.get('content-type')?.includes('json'))throw Error('OFF unavailable');return r.json();}
function allocate(pool,s,partial=false){
const needs={nutri:s.count,nova:s.novaCount,eco:s.ecoCount},slots=Object.entries(needs).flatMap(([m,n])=>Array(n).fill(m));const candidates=slots.map(m=>pool.map((p,i)=>eligible(p,s.country,m)?i:-1).filter(i=>i>=0)),owners=new Map(),picked=Array(slots.length).fill(-1);
function assign(slot,seen){for(const i of candidates[slot]){if(seen.has(i))continue;seen.add(i);if(!owners.has(i)||assign(owners.get(i),seen)){owners.set(i,slot);picked[slot]=i;return true;}}return false;}
for(const slot of candidates.map((_,i)=>i).sort((a,b)=>partial&&(a===0||b===0)?a===0?-1:1:candidates[a].length-candidates[b].length))if(!assign(slot,new Set())&&!partial)return null;
if(!partial)return picked.map(i=>pool[i]);
if(picked[0]<0)return null;
const counts={count:0,novaCount:0,ecoCount:0},keys={nutri:'count',nova:'novaCount',eco:'ecoCount'};
const deck=picked.flatMap((i,slot)=>{if(i<0)return [];counts[keys[slots[slot]]]++;return [pool[i]];});
return{deck,counts};}
async function checkPhoto(url,signal){
 // Some image hosts refuse HEAD; verify with a small GET before rejecting them.
 for(const method of ['HEAD','GET']){let target=url;try{for(let redirects=0;redirects<3;redirects++){
  const r=await fetch(target,{method,redirect:'manual',headers:method==='GET'?{Range:'bytes=0-511'}:{},signal:signal?AbortSignal.any([signal,AbortSignal.timeout(4500)]):AbortSignal.timeout(4500)});
  if(r.status>=300&&r.status<400){const next=new URL(r.headers.get('location')||'',target);await r.body?.cancel();if(next.protocol!=='https:'||next.hostname!=='images.openfoodfacts.org')return 'missing';target=next.href;continue;}
  const status=r.status,valid=r.ok&&/^image\//i.test(r.headers.get('content-type')||'');await r.body?.cancel();
  if(valid)return 'ok';if(status===404||status===410||r.ok)return 'missing';break;
 }}catch{}}
 return 'unavailable';
}
async function draw(env,s,signal){const country=s.country,now=Date.now(),page=1+Math.floor(Math.random()*20),key='v8-off-'+country+'-'+page;const cached=await db(env).prepare('SELECT payload FROM off_cache WHERE id=? AND expires_at>?').bind(key,now).first();let pool=cached?JSON.parse(cached.payload):[],source='Open Food Facts · recherche',searchSucceeded=!!cached;
if(!allocate(pool,s)){
 const requested=[s.count?'nutriscore_grade:(a OR b OR c OR d OR e)':null,s.novaCount?'nova_groups:(1 OR 2 OR 3 OR 4)':null,s.ecoCount?'ecoscore_grade:(a OR b OR c OR d OR e)':null].filter(Boolean).join(' OR ');
 const q=(country==='world'?'':`countries_tags:"en:${country}" AND `)+'('+requested+')';
 // Search-a-licious is the primary source; page one rescues sparse random pages.
 for(const pg of [...new Set([page,1])]){const u=new URL('https://search.openfoodfacts.org/search');u.search=new URLSearchParams({q,page:String(pg),page_size:'100',langs:'fr,en',fields:fields.join(',')});try{const data=await offJSON(u,7000,signal);if(!Array.isArray(data.hits))throw Error('Invalid search response');searchSucceeded=true;pool=[...new Map([...pool,...data.hits.map(normalized)].map(p=>[p.code,p])).values()];if(allocate(pool,s))break;}catch{}}
 if(!allocate(pool,s)){try{const u=new URL('https://world.openfoodfacts.org/api/v2/search');u.search=new URLSearchParams({page:'1',page_size:'100',sort_by:'unique_scans_n',fields:fields.join(','),...(country==='world'?{}:{countries_tags:'en:'+country})});const data=await offJSON(u,3500,signal);if(!Array.isArray(data.products))throw Error('Invalid search response');searchSucceeded=true;pool=[...new Map([...pool,...data.products.map(normalized)].map(p=>[p.code,p])).values()];}catch{}}
 if(!searchSucceeded)fail('Open Food Facts est indisponible. Réessaie dans un instant.',503);
 if(!allocate(pool,s,true))fail('Aucun produit admissible trouvé dans ce tirage. Réessaie.',503);
 await db(env).prepare('INSERT INTO off_cache(id,payload,expires_at) VALUES(?,?,?) ON CONFLICT(id) DO UPDATE SET payload=excluded.payload,expires_at=excluded.expires_at').bind(key,JSON.stringify(pool),now+3600000).run();
}
// Revalidate selected records and actual image availability before committing the deck.
const checked=new Set(),photos=new Map();let photoUnavailable=false;pool=shuffle(pool.slice());
for(let attempt=0;attempt<4;attempt++){
 const selection=allocate(pool,s,true);if(!selection)break;const deck=selection.deck;let cursor=0;
 await Promise.all(Array.from({length:Math.min(6,deck.length)},async()=>{while(cursor<deck.length){const p=deck[cursor++];if(checked.has(p.code))continue;checked.add(p.code);let fresh=p;
 try{const d=await offJSON('https://world.openfoodfacts.org/api/v2/product/'+p.code+'.json?fields='+fields.join(','),1500,signal);if(d.status===0){pool=pool.filter(x=>x.code!==p.code);continue;}if(d.product){fresh=normalized(d.product);if(fresh.code!==p.code){pool=pool.filter(x=>x.code!==p.code);continue;}}}catch{}
 let available=false;const url=fresh.image_front_url;
 if(/^https:\/\/images\.openfoodfacts\.org\//.test(url||'')){if(!photos.has(url))photos.set(url,checkPhoto(url,signal));const result=await photos.get(url);available=result==='ok';photoUnavailable ||= result==='unavailable';}
 pool=available?pool.map(x=>x.code===p.code?fresh:x):pool.filter(x=>x.code!==p.code);
 }}));
 const verified=allocate(pool,s,true);if(verified&&verified.deck.every(p=>checked.has(p.code)))return{...verified,source};
}
const fallback=allocate(pool.filter(p=>checked.has(p.code)),s,true);if(fallback)return{...fallback,source};
fail(photoUnavailable?'Vérification des photos indisponible. Réessaie dans un instant.':'Aucune photo accessible dans ce tirage. Réessaie.',503);}

const number=n=>Number(n).toLocaleString('fr-CA',{maximumFractionDigits:2});
const finite=n=>typeof n==='number'&&Number.isFinite(n);
const NOVA_TEXT={1:'Aliment non transformé ou peu transformé',2:'Ingrédient culinaire transformé',3:'Aliment transformé',4:'Produit ultra-transformé'};
function insights(p,m){const points=[],out={title:'Les repères de cette fiche',points,note:'',url:'https://world.openfoodfacts.org/product/'+p.code};const n=p.nutriments||{};
if(m==='nutri'){const record=p.nutriscore?.[String(p.nutriscore_version)],verified=record&&record.grade===p.nutriscore_grade;const data=verified?record.data:p.nutriscore_data?.grade===p.nutriscore_grade?p.nutriscore_data:null;
const names={energy:'Calories',sugars:'Sucres',saturated_fat:'Graisses saturées',salt:'Sel',sodium:'Sodium',fiber:'Fibres',proteins:'Protéines',fruits_vegetables_legumes:'Fruits, légumes et légumineuses',fruits_vegetables_nuts_colza_walnut_olive_oils:'Fruits, légumes, noix et huiles prises en compte'};
if(data?.components){out.title='Ce qui pèse dans cette note';const neg=(data.components.negative||[]).filter(c=>c.points>0).sort((a,b)=>b.points-a.points),pos=(data.components.positive||[]).filter(c=>c.points>0&&(c.id!=='proteins'||data.count_proteins!==0)).sort((a,b)=>b.points-a.points);
for(const [c,kind]of Array.from({length:Math.max(neg.length,pos.length)},(_,i)=>[neg[i]&&[neg[i],'défavorables'],pos[i]&&[pos[i],'favorables']].filter(Boolean)).flat())points.push({label:names[c.id]||c.id.replaceAll('_',' '),text:`${number(c.id==='energy'&&/^kj$/i.test(c.unit)?c.value/4.184:c.value)} ${c.id==='energy'&&/^kj$/i.test(c.unit)?'kcal':c.unit}${c.unit==='%'?' de la composition':' pour 100 g / 100 ml'} · ${c.points} point${c.points>1?'s':''} ${kind}.`,tone:kind==='favorables'?'good':'warm'});
if(!points.length&&finite(data.negative_points)&&finite(data.positive_points))points.push({label:'Le bilan du calcul',text:`${data.negative_points} points défavorables, compensés par ${data.positive_points} points favorables.`,tone:'neutral'});
out.note='Détail du calcul renseigné par Open Food Facts'+(p.nutriscore_version?' · version '+p.nutriscore_version:'')+'.';}
if(!points.length){for(const [id,label,help]of [['sugars_100g','Sucres','Les sucres entrent dans les points défavorables.'],['saturated-fat_100g','Graisses saturées','Elles entrent dans les points défavorables.'],['fiber_100g','Fibres','Elles peuvent apporter des points favorables.'],['salt_100g','Sel','Le sel entre dans les points défavorables.']]){if(finite(n[id])&&points.length<4)points.push({label,text:`${number(n[id])} g pour 100 g / 100 ml. ${help}`,tone:id==='fiber_100g'?'good':'warm'});}out.note='Le détail du calcul n’est pas fourni. Ces valeurs sont des repères, pas une reconstitution de la note.';}}
if(m==='nova'){points.push({label:'Groupe '+p.nova_group,text:NOVA_TEXT[p.nova_group]+'. NOVA décrit le degré et le but de la transformation.',tone:'neutral'});const map={'en:whey':'lactosérum','en:sugar':'sucre','en:milk-powder':'lait en poudre','en:flavouring':'arôme','en:maltodextrin':'maltodextrine','en:glucose-syrup':'sirop de glucose','en:e322':'lécithines (E322)','en:modified-starch':'amidon modifié'};const markers=p.nova_groups_markers?.[String(p.nova_group)]||[];if(Array.isArray(markers)&&markers.length)points.push({label:'Marqueurs repérés par OFF',text:markers.slice(0,3).map(x=>{const id=Array.isArray(x)?x[1]:'';return map[id]||String(id).replace(/^\w\w:/,'').replaceAll('-',' ');}).filter(Boolean).join(' · ')+'.',tone:'warm'});out.note=markers.length?'Classification et marqueurs renseignés par Open Food Facts.':'OFF fournit ce groupe, sans ses marqueurs détaillés pour cette fiche.';}
if(m==='eco'){const e=p.ecoscore_data||{};if(e.grade===p.ecoscore_grade){out.title='Ce qui compose cette note';if(finite(e.agribalyse?.score))points.push({label:'Base environnementale',text:`${number(e.agribalyse.score)} / 100 avant les ajustements${e.agribalyse.name_fr?' · catégorie « '+e.agribalyse.name_fr+' »':''}.`,tone:'neutral'});const adj=e.adjustments||{};for(const [key,label]of [['packaging','Emballage'],['production_system','Mode de production'],['origins_of_ingredients','Origine des ingrédients'],['threatened_species','Biodiversité']]){const v=adj[key]?.value;if(finite(v)&&v!==0&&points.length<4)points.push({label,text:`${v>0?'+':''}${number(v)} points dans le calcul OFF${adj[key].warning?' · des informations sont manquantes ou estimées':''}.`,tone:v>0?'good':'warm'});}if(points.length<4&&finite(e.score))points.push({label:'Score renseigné',text:`${number(e.score)} / 100 après les ajustements.`,tone:'neutral'});out.note='Détail environnemental fourni par Open Food Facts; certaines données peuvent être estimées.';}
if(!points.length){out.note='Le détail du calcul est absent de cette fiche. Nous ne déduisons pas de cause particulière à cette lettre.';}}
const grade=m==='nutri'?p.nutriscore_grade:m==='eco'?p.ecoscore_grade:null;
out.points=points.filter(point=>grade==='a'?point.tone!=='warm':['d','e'].includes(grade)?point.tone!=='good':true).slice(0,4);
return out;}
async function body(request){if(Number(request.headers.get('content-length')||0)>4096)fail('Requête trop volumineuse.',413);const text=await request.text();if(text.length>4096)fail('Requête trop volumineuse.',413);try{return JSON.parse(text);}catch{fail('Requête invalide.');}}
async function api(request,env,ctx){const url=new URL(request.url);if(!['GET','POST'].includes(request.method))fail('Méthode invalide.',405);if(request.method==='POST'&&(request.headers.get('origin')&&request.headers.get('origin')!==url.origin))fail('Origine refusée.',403);
const raw=request.headers.get('Authorization')?.replace(/^Bearer /,'')||'';if(!/^[a-f0-9]{64}$/.test(raw))fail('Profil absent. Recharge la page.',401);const token=await hash(raw);
if(url.pathname==='/api/rooms'&&request.method==='POST'){const b=await body(request),who=profile(b),opts=options(b);if(!/^[a-f0-9]{32}$/.test(b.operation||''))fail('Identifiant de création invalide.');const me={id:rid(),token,...who,score:0,base:0,vote:null,award:0,ready:false,stats:freshStats()},id=(await hash(token+b.operation)).slice(0,32);const s={id,phase:'lobby',gameId:rid(),step:rid(),host:me.id,players:[me],...opts,round:0,deck:[],history:[],createdAt:Date.now()};s.schedule=schedule(s);await db(env).prepare('INSERT OR IGNORE INTO rooms(id,state,version,updated_at) VALUES(?,?,0,?)').bind(id,JSON.stringify(s),Date.now()).run();return json(project((await read(env,id)).s,token));}
const match=url.pathname.match(/^\/api\/rooms\/([a-f0-9]{32})(?:\/(join|profile|settings|start|vote|ready|next|skip|lobby|leave))?$/);if(!match)fail('Route introuvable.',404);const [,id,action]=match;
if(request.method==='GET'&&!action){let {s}=await read(env,id);const before=JSON.stringify([s.phase,s.round,s.step]);advance(s,Date.now());if(JSON.stringify([s.phase,s.round,s.step])!==before)s=await mutate(env,id,()=>{});return json(project(s,token));}
if(request.method!=='POST'||!action)fail('Route introuvable.',404);const b=await body(request);
if(action==='start'){const job=rid();const loading=await mutate(env,id,s=>{host(s,token);if(s.phase!=='lobby')fail('La partie est déjà démarrée.',409);s.phase='loading';s.loadingAt=Date.now();s.loadingJob=job;s.error=null;});const run=async()=>{try{const {s}=await read(env,id);const slots=s.roulette?Array.from({length:s.questionCount},randomSlot):null,planned=slots?.map(slotMode),drawOptions=planned?{...s,count:planned.filter(m=>m==='nutri').length,novaCount:planned.filter(m=>m==='nova').length,ecoCount:planned.filter(m=>m==='eco').length}:s;const controller=new AbortController();let timer;const timeout=new Promise((_,reject)=>{timer=setTimeout(()=>{controller.abort();reject(Object.assign(new Error('Open Food Facts met trop de temps à répondre. Réessaie.'),{status:503}));},24000);});let drawn;try{drawn=await Promise.race([draw(env,drawOptions,controller.signal),timeout]);}finally{clearTimeout(timer);}const next=await mutate(env,id,r=>{if(r.phase!=='loading'||r.loadingJob!==job)fail('Le tirage a expiré. Réessaie.',409);r.requestedTotal=schedule(r).length;Object.assign(r,drawn.counts);r.deck=drawn.deck;r.source=drawn.source;r.schedule=schedule(r);if(planned){const buckets={nutri:[],nova:[],eco:[]};r.schedule.forEach((m,i)=>buckets[m].push(r.deck[i]));const deck=[],actual=[],wheelSlots=[];planned.forEach((m,i)=>{if(buckets[m].length){deck.push(buckets[m].shift());actual.push(m);wheelSlots.push(slots[i]);}});r.deck=deck;r.schedule=actual;r.wheelSlots=wheelSlots;r.requestedTotal=s.questionCount;}r.round=0;r.history=[];r.scoreUnit=100;r.gameId=rid();r.deadline=null;r.lockAt=null;r.landAt=null;r.resultAt=null;r.players.forEach(p=>{p.score=0;p.base=0;p.vote=null;p.award=0;p.stats=freshStats();});if(r.roulette)enterWheel(r,Date.now());else newGate(r,'intro',Date.now());});return json(project(next,token));}catch(e){await mutate(env,id,s=>{if(s.phase==='loading'&&s.loadingJob===job){s.phase='lobby';s.error=e.status?e.message:'Le tirage a échoué. Réessaie.';}});throw e;}};if(ctx?.waitUntil){ctx.waitUntil(run().catch(e=>console.error('NutriDeck draw',e.message)));return json(project(loading,token),202);}return run();}
const s=await mutate(env,id,s=>{
if(action==='join'){if(s.players.find(p=>p.token===token))return;if(s.phase!=='lobby')fail('La partie a commencé. Attends le retour au salon.',409);if(s.players.length>=8)fail('Le salon est complet (8 joueurs).');s.players.push({id:rid(),token,...profile(b),score:0,base:0,vote:null,award:0,ready:false,stats:freshStats()});return;}
const me=member(s,token);
if(action==='profile'){if(s.phase!=='lobby')fail('Les profils sont fixés pendant la partie.',409);Object.assign(me,profile(b));}
if(action==='settings'){host(s,token);if(s.phase!=='lobby')fail('La partie est déjà démarrée.',409);Object.assign(s,options(b));s.schedule=schedule(s);}
if(action==='vote'){if(s.phase!=='vote'||b.round!==s.round+1||(s.gameId!=='legacy'&&b.gameId!==s.gameId))fail('Les votes sont verrouillés.',409);if(!choices(mode(s)).includes(b.choice))fail('Vote invalide.');me.vote=b.choice;if(!s.deadline)s.deadline=Date.now()+s.seconds*1000;if(s.players.every(p=>p.vote))lock(s,Date.now());}
if(action==='ready'){if(s.roulette&&(s.readyEnabled===false||s.phase!=='results'))fail('Le passage est automatique.',409);if(!['intro','results'].includes(s.phase)||b.step!==s.step||b.gameId!==s.gameId)fail('Cette étape est déjà terminée.',409);me.ready=b.ready!==false;advance(s,Date.now());}
if(action==='next')fail('Chaque joueur doit maintenant utiliser « Prêt ». Recharge la page pour la nouvelle version.',409);
if(action==='skip'){host(s,token);if(s.phase!=='vote'||b.round!==s.round+1||(s.gameId!=='legacy'&&b.gameId!==s.gameId))fail('La manche est déjà verrouillée.',409);s.skipped=true;s.players.forEach(p=>p.vote=null);lock(s,Date.now());}
if(action==='lobby'){host(s,token);if(s.phase!=='finished')fail('La partie est encore en cours.',409);s.lastFinal??=snapshot(s);s.phase='lobby';s.step=rid();s.deck=[];s.round=0;s.deadline=null;s.lockAt=null;s.readyDeadline=null;s.players.forEach(p=>p.ready=false);}
if(action==='leave'){if(!['finished','lobby'].includes(s.phase))fail('Tu peux quitter après la partie. Fermer le navigateur conserve ta place.',409);if(s.phase==='finished')s.lastFinal??=snapshot(s);s.players=s.players.filter(p=>p.id!==me.id);if(s.host===me.id)s.host=s.players[0]?.id||null;}
});return json(project(s,token));}
export default {async fetch(request,env,ctx){try{const url=new URL(request.url);if(url.pathname.startsWith('/api/'))return await api(request,env,ctx);const path=url.pathname==='/'?'/index.html':url.pathname;const f=STATIC_FILES[path];if(!f)return new Response('Introuvable',{status:404});if(!['GET','HEAD'].includes(request.method))return new Response('Méthode invalide',{status:405});return new Response(request.method==='HEAD'?null:Uint8Array.from(atob(f.data),c=>c.charCodeAt(0)),{headers:{'Content-Type':f.type,'Cache-Control':/\.html$|\.js$|\.css$/.test(path)?'no-cache':'public, max-age=3600','X-Content-Type-Options':'nosniff','Referrer-Policy':'same-origin'}});}catch(e){if(!e.status)console.error('NutriDeck API',e.message);return json({error:e.status?e.message:'Connexion interrompue. Ta partie est conservée; réessaie.'},e.status||503);}}};
