// All game transitions are durable and serialized with a D1 room-version CAS.
const AVATARS=['😀','🦊','🐼','🐸','🦁','🐙','🐵','🐯','🐨','🐧','🦄','🐻','🐮','🐷','🐹','🐰','🤖','🧓','🧢'];
const COUNTRIES={canada:'Canada',france:'France',belgium:'Belgique',switzerland:'Suisse','united-states':'États-Unis','united-kingdom':'Royaume-Uni',germany:'Allemagne',spain:'Espagne',italy:'Italie',portugal:'Portugal',australia:'Australie',world:'Tous les pays'};
const MODE_NAMES={nutri:'Nutri-Score',nova:'NOVA',eco:'Éco-Score'};
const choices=mode=>mode==='nova'?['1','2','3','4']:['A','B','C','D','E'];
const json=(v,status=200)=>Response.json(v,{status,headers:{'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});
function fail(message,status=400){throw Object.assign(new Error(message),{status});}
const db=env=>{if(!env.DB)fail('Le salon est temporairement indisponible.',503);return env.DB;};
const hash=async s=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s))),x=>x.toString(16).padStart(2,'0')).join('');
const rid=()=>crypto.randomUUID().replaceAll('-','');
function profile(b){const name=String(b.name||'').trim().replace(/[\x00-\x1f]/g,'').slice(0,24);if(!name)fail('Choisis ton nom.');if(!AVATARS.includes(b.avatar))fail('Choisis un avatar.');return{name,avatar:b.avatar};}
function options(b){const count=Number(b.count),seconds=Number(b.seconds),novaCount=Number(b.novaCount??0),ecoCount=Number(b.ecoCount??0),readySeconds=Number(b.readySeconds??30),country=b.country||'canada';if(!Number.isInteger(count)||count<1||count>20||![12,20,30,45].includes(seconds)||![15,30,45,60,90].includes(readySeconds)||![novaCount,ecoCount].every(n=>Number.isInteger(n)&&n>=0&&n<=5)||!Object.hasOwn(COUNTRIES,country))fail('Vérifie les réglages de la partie.');return{count,seconds,novaCount,ecoCount,readySeconds,country};}
const freshStats=()=>({exact:0,streak:0,bestStreak:0,answered:0,worst:null});
const schedule=s=>[...Array(s.count).fill('nutri'),...Array(s.novaCount||0).fill('nova'),...Array(s.ecoCount||0).fill('eco')];
const mode=s=>s.schedule?.[s.round]||'nutri';
const answer=s=>mode(s)==='nova'?String(s.deck[s.round].nova_group):String(s.deck[s.round][mode(s)==='eco'?'ecoscore_grade':'nutriscore_grade']).toUpperCase();
function upgrade(s){s.novaCount??=0;s.ecoCount??=0;s.readySeconds??=30;s.country??='world';s.schedule??=schedule(s);s.gameId??='legacy';s.step??='legacy-'+s.round+'-'+s.phase;s.history??=[];s.players.forEach(p=>{p.stats??=freshStats();p.ready??=false;});if(s.phase==='reveal'){s.landAt??=s.lockAt+4300;s.resultAt??=s.lockAt+9000;s.revealPlan??=[{at:900,value:answer(s)},{at:4300,value:answer(s)}];}if(s.phase==='results')s.readyDeadline??=(s.lockAt||s.createdAt)+9000+s.readySeconds*1000;if(s.phase==='finished'&&!s.lastFinal)s.lastFinal=snapshot(s);return s;}
async function read(env,id){const r=await db(env).prepare('SELECT state,version FROM rooms WHERE id=?').bind(id).first();if(!r)fail('Ce salon est introuvable. Vérifie le lien.',404);const s=upgrade(JSON.parse(r.state));s.revision=r.version;return{s,version:r.version};}
function newGate(s,phase,now){s.phase=phase;s.step=rid();s.readyDeadline=now+s.readySeconds*1000;s.players.forEach(p=>p.ready=false);}
function enterVote(s){s.phase='vote';s.step=rid();s.deadline=null;s.readyDeadline=null;s.lockAt=null;s.landAt=null;s.resultAt=null;s.skipped=false;s.players.forEach(p=>{p.ready=false;p.vote=null;p.award=0;p.base=p.score;});}
function nextRound(s,now){const old=mode(s);s.round++;if(mode(s)!==old)newGate(s,'intro',now);else enterVote(s);}
function rollPlan(target,vals,lastStyle){const styles=['direct','reverse','suspense'].filter(x=>x!==lastStyle),style=styles[Math.floor(Math.random()*styles.length)],index=vals.indexOf(target),n=vals.length,cycles=4+Math.floor(Math.random()*3),duration=3200+Math.floor(Math.random()*1100),plan=[];
const end=style==='direct'?index:(index+(style==='reverse'?2:1))%n,steps=cycles*n+end;
for(let i=0;i<=steps;i++){const at=900+Math.round((duration*(style==='direct'?1:.72))*Math.pow(i/steps,1.8));plan.push({at,value:vals[i%n]});}
if(style==='reverse'){plan.push({at:900+Math.round(duration*.84),value:vals[(index+1)%n]},{at:900+duration,value:target});}
if(style==='suspense'){plan.push({at:900+Math.round(duration*.81),value:target},{at:900+Math.round(duration*.91),value:vals[(index+n-1)%n]},{at:900+duration,value:target});}
return{style,plan,duration:duration+900};}
function lock(s,now){s.phase='reveal';s.step=rid();s.lockAt=now;s.deadline=null;s.readyDeadline=null;const correct=answer(s),vals=choices(mode(s)),roll=rollPlan(correct,vals,s.revealStyle);s.revealStyle=roll.style;s.revealPlan=roll.plan;s.landAt=now+roll.duration;s.resultAt=s.landAt+4700;
for(const p of s.players){p.base=p.score;const distance=p.vote==null?null:Math.abs(vals.indexOf(p.vote)-vals.indexOf(correct));p.award=s.skipped||distance===null?0:([1000,600,250][distance]||0);p.score+=p.award;if(!s.skipped){const st=p.stats;st.answered+=distance===null?0:1;st.streak=distance===0?st.streak+1:0;st.bestStreak=Math.max(st.bestStreak,st.streak);if(distance===0)st.exact++;if(distance!==null&&distance>0&&(!st.worst||distance/(vals.length-1)>st.worst.ratio))st.worst={distance,ratio:distance/(vals.length-1),max:vals.length-1,mode:mode(s),guess:p.vote,answer:correct,product:s.deck[s.round].product_name_fr||s.deck[s.round].product_name};}}
s.history.push({round:s.round+1,mode:mode(s),code:s.deck[s.round].code,name:s.deck[s.round].product_name_fr||s.deck[s.round].product_name,answer:correct,skipped:!!s.skipped,insights:insights(s.deck[s.round],mode(s))});}
function snapshot(s){return{gameId:s.gameId,statsAvailable:s.gameId!=='legacy',country:s.country,total:s.schedule.length,counts:{nutri:s.count,nova:s.novaCount,eco:s.ecoCount},history:s.history,players:s.players.map(p=>({id:p.id,name:p.name,avatar:p.avatar,score:p.score,stats:p.stats}))};}
function advance(s,now){if(s.phase==='loading'&&now-s.loadingAt>150000){s.phase='lobby';s.error='Le chargement a été interrompu. Tu peux réessayer.';}
if(s.phase==='vote'&&s.deadline&&now>=s.deadline)lock(s,s.deadline);
if(s.phase==='reveal'&&now>=s.resultAt){if(s.round+1>=s.schedule.length){s.phase='finished';s.readyDeadline=null;s.lastFinal=snapshot(s);}else newGate(s,'results',now);}
if(['intro','results'].includes(s.phase)&&((s.readyDeadline&&now>=s.readyDeadline)||s.players.every(p=>p.ready))){if(s.phase==='intro')enterVote(s);else nextRound(s,now);}}
async function mutate(env,id,fn){for(let i=0;i<12;i++){const {s,version}=await read(env,id);advance(s,Date.now());await fn(s);s.revision=version+1;const r=await db(env).prepare('UPDATE rooms SET state=?,version=version+1,updated_at=? WHERE id=? AND version=?').bind(JSON.stringify(s),Date.now(),id,version).run();if(r.meta.changes)return s;}fail('La table se synchronise. Réessaie.',409);}
function member(s,token){const p=s.players.find(p=>p.token===token);if(!p)fail('Rejoins le salon avec ton profil.',401);return p;}
function host(s,token){const p=member(s,token);if(p.id!==s.host)fail('Seul l’hôte peut faire cette action.',403);return p;}
function safeProduct(p,landed){if(!p)return null;const o={};for(const k of CARD_FIELDS)if(p[k]!=null)o[k]=p[k];if(!landed){delete o.nutriscore_grade;delete o.nova_group;delete o.ecoscore_grade;}return o;}
function project(s,token){const me=s.players.find(p=>p.token===token),now=Date.now(),locked=['reveal','results','finished'].includes(s.phase),landed=['results','finished'].includes(s.phase)||(s.phase==='reveal'&&now>=s.landAt),current=mode(s);const product=me&&s.phase!=='intro'?safeProduct(s.deck?.[s.round],landed):null;
return{id:s.id,revision:s.revision||0,phase:s.phase,gameId:s.gameId,step:s.step,host:s.host,me:me?.id||null,count:s.count,novaCount:s.novaCount,ecoCount:s.ecoCount,country:s.country,seconds:s.seconds,readySeconds:s.readySeconds,round:s.round+1,total:s.schedule.length,mode:current,phaseRound:s.schedule.slice(0,s.round+1).filter(m=>m===current).length,phaseTotal:s.schedule.filter(m=>m===current).length,serverNow:now,deadline:s.deadline||null,readyDeadline:s.readyDeadline||null,lockAt:s.lockAt||null,landAt:s.landAt||null,resultAt:s.resultAt||null,landed,skipped:!!s.skipped,error:s.error||null,source:s.source||null,revealTarget:me&&locked?answer(s):null,revealPlan:me&&locked?s.revealPlan:null,product,insights:me&&landed?insights(s.deck[s.round],current):null,lastFinal:me&&['finished','lobby'].includes(s.phase)?s.lastFinal||null:null,players:s.players.map(p=>({id:p.id,name:p.name,avatar:p.avatar,score:landed||s.phase==='lobby'||s.phase==='intro'?p.score:(p.base??p.score),base:p.base??p.score,award:landed?p.award||0:0,stats:landed||['lobby','intro'].includes(s.phase)?p.stats:null,ready:!!p.ready,voted:!!p.vote,vote:me&&(locked||p.id===me.id)?p.vote:null,host:p.id===s.host}))};}
const CARD_FIELDS=['code','product_name','product_name_fr','brands','quantity','image_front_url','nutriscore_grade','nova_group','ecoscore_grade','nutriments','ingredients_text','ingredients_text_fr','allergens_tags','traces_tags','additives_tags','additives_n'];
const fields=[...CARD_FIELDS,'countries_tags','nutrition_grades','nova_groups','nutriscore_version','nutriscore','nutriscore_data','nova_groups_markers','ecoscore_data'];
function normalized(p){const o={};for(const k of fields)if(p[k]!=null)o[k]=p[k];o.code=String(o.code||'');o.brands=Array.isArray(o.brands)?o.brands.join(', '):o.brands||'';o.nutriscore_grade=String(o.nutriscore_grade||o.nutrition_grades||'').toLowerCase();o.nova_group=Number(o.nova_group||o.nova_groups)||null;delete o.nutrition_grades;delete o.nova_groups;
if(o.ecoscore_data){const e=o.ecoscore_data;o.ecoscore_data={grade:e.grade,score:e.score,agribalyse:{score:e.agribalyse?.score,name_fr:e.agribalyse?.name_fr},adjustments:Object.fromEntries(Object.entries(e.adjustments||{}).map(([k,v])=>[k,{value:v.value,warning:v.warning}]))};}
if(o.nutriscore&&o.nutriscore_version)o.nutriscore={[String(o.nutriscore_version)]:o.nutriscore[String(o.nutriscore_version)]};
return o;}
function eligible(p,country,m){const score=m==='nova'?[1,2,3,4].includes(p.nova_group):/^[a-e]$/.test(p[m==='eco'?'ecoscore_grade':'nutriscore_grade']||'');return score&&/^\d{4,24}$/.test(p.code)&&!!(p.product_name_fr||p.product_name)&&/^https:\/\/images\.openfoodfacts\.org\//.test(p.image_front_url||'')&&(country==='world'||p.countries_tags?.includes('en:'+country))&&(m!=='nutri'||['energy-kcal_100g','energy-kj_100g','sugars_100g','salt_100g','saturated-fat_100g','proteins_100g'].filter(k=>Number.isFinite(p.nutriments?.[k])).length>=4);}
const shuffle=a=>{for(let i=a.length-1;i>0;i--){const bytes=new Uint32Array(1);crypto.getRandomValues(bytes);const j=bytes[0]%(i+1);[a[i],a[j]]=[a[j],a[i]];}return a;};
async function offJSON(url,timeout=12000){const r=await fetch(url,{headers:{'User-Agent':'NutriDeckGym/0.7 (https://github.com/jutrasimon/nutrideck)','Accept':'application/json'},signal:AbortSignal.timeout(timeout)});if(!r.ok||!r.headers.get('content-type')?.includes('json'))throw Error('OFF unavailable');return r.json();}
function allocate(pool,s){
const needs={nutri:s.count,nova:s.novaCount,eco:s.ecoCount},slots=Object.entries(needs).flatMap(([m,n])=>Array(n).fill(m));const candidates=slots.map(m=>pool.map((p,i)=>eligible(p,s.country,m)?i:-1).filter(i=>i>=0)),owners=new Map(),picked=Array(slots.length).fill(-1);
function assign(slot,seen){for(const i of candidates[slot]){if(seen.has(i))continue;seen.add(i);if(!owners.has(i)||assign(owners.get(i),seen)){owners.set(i,slot);picked[slot]=i;return true;}}return false;}
for(const slot of candidates.map((_,i)=>i).sort((a,b)=>candidates[a].length-candidates[b].length))if(!assign(slot,new Set()))return null;
return picked.map(i=>pool[i]);}
async function draw(env,s){const country=s.country,now=Date.now(),page=1+Math.floor(Math.random()*75),key='v7-off-'+country+'-'+page;const cached=await db(env).prepare('SELECT payload FROM off_cache WHERE id=? AND expires_at>?').bind(key,now).first();let pool=cached?JSON.parse(cached.payload):[],source='Open Food Facts';
if(!allocate(pool,s)){const lease=await db(env).prepare('INSERT INTO off_cache(id,payload,expires_at) VALUES(?,?,?) ON CONFLICT(id) DO UPDATE SET expires_at=excluded.expires_at WHERE off_cache.expires_at<?').bind('search-lease','{}',now+20000,now).run();if(!lease.meta.changes)fail('Un tirage est déjà en cours. Réessaie dans quelques secondes.',429);
try{const u=new URL('https://world.openfoodfacts.org/api/v2/search');u.search=new URLSearchParams({page:String(page),page_size:'100',sort_by:'unique_scans_n',fields:fields.join(','),...(country==='world'?{}:{countries_tags:'en:'+country})});const data=await offJSON(u,9000);pool=(data.products||[]).map(normalized);}catch{pool=[];}
if(!allocate(pool,s)){const requested=[s.count?'nutriscore_grade:(a OR b OR c OR d OR e)':null,s.novaCount?'nova_groups:(1 OR 2 OR 3 OR 4)':null,s.ecoCount?'ecoscore_grade:(a OR b OR c OR d OR e)':null].filter(Boolean).join(' OR ');const q=(country==='world'?'':`countries_tags:"en:${country}" AND `)+'('+requested+')';
for(const pg of [page,1]){const u=new URL('https://search.openfoodfacts.org/search');u.search=new URLSearchParams({q,page:String(pg),page_size:'100',langs:'fr,en',fields:fields.join(',')});try{const data=await offJSON(u,16000);pool=[...new Map([...pool,...(data.hits||[]).map(normalized)].map(p=>[p.code,p])).values()];source='Open Food Facts · recherche';if(allocate(pool,s))break;}catch{if(pg===1&&pool.length===0)fail('Open Food Facts ne répond pas. Le salon est conservé; réessaie le tirage.',503);}}}
if(!allocate(pool,s))fail(`Pas assez de fiches avec photo et scores pour ${COUNTRIES[country]}. Réduis les quantités, désactive un bonus ou réessaie. Aucun produit d’un autre pays n’a été ajouté.`,503);
await db(env).prepare('INSERT INTO off_cache(id,payload,expires_at) VALUES(?,?,?) ON CONFLICT(id) DO UPDATE SET payload=excluded.payload,expires_at=excluded.expires_at').bind(key,JSON.stringify(pool),now+3600000).run();}
const deck=allocate(shuffle(pool.slice()),s),modes=schedule(s);let cursor=0;await Promise.all(Array.from({length:Math.min(5,deck.length)},async()=>{while(cursor<deck.length){const i=cursor++,p=deck[i];try{const d=await offJSON('https://world.openfoodfacts.org/api/v2/product/'+p.code+'.json?fields='+fields.join(','),4500);if(d.product){const fresh=normalized(d.product);if(fresh.code===p.code&&eligible(fresh,country,modes[i]))deck[i]=fresh;}}catch{}}}));return{deck,source};}
const number=n=>Number(n).toLocaleString('fr-CA',{maximumFractionDigits:2});
const finite=n=>typeof n==='number'&&Number.isFinite(n);
const NOVA_TEXT={1:'Aliment non transformé ou peu transformé',2:'Ingrédient culinaire transformé',3:'Aliment transformé',4:'Produit ultra-transformé'};
function insights(p,m){const points=[],out={title:'Les repères de cette fiche',points,note:'',url:'https://world.openfoodfacts.org/product/'+p.code};const n=p.nutriments||{};
if(m==='nutri'){const record=p.nutriscore?.[String(p.nutriscore_version)],verified=record&&record.grade===p.nutriscore_grade;const data=verified?record.data:p.nutriscore_data?.grade===p.nutriscore_grade?p.nutriscore_data:null;
const names={energy:'Énergie',sugars:'Sucres',saturated_fat:'Graisses saturées',salt:'Sel',sodium:'Sodium',fiber:'Fibres',proteins:'Protéines',fruits_vegetables_legumes:'Fruits, légumes et légumineuses',fruits_vegetables_nuts_colza_walnut_olive_oils:'Fruits, légumes, noix et huiles prises en compte'};
if(data?.components){out.title='Ce qui pèse dans cette note';const neg=(data.components.negative||[]).filter(c=>c.points>0).sort((a,b)=>b.points-a.points),pos=(data.components.positive||[]).filter(c=>c.points>0&&(c.id!=='proteins'||data.count_proteins!==0)).sort((a,b)=>b.points-a.points);
for(const [c,kind]of [...neg.slice(0,2).map(c=>[c,'défavorables']),...pos.slice(0,1).map(c=>[c,'favorables'])])points.push({label:names[c.id]||c.id.replaceAll('_',' '),text:`${number(c.value)} ${c.unit}${c.unit==='%'?' de la composition':' pour 100 g / 100 ml'} · ${c.points} point${c.points>1?'s':''} ${kind}.`,tone:kind==='favorables'?'good':'warm'});
if(points.length<3&&finite(data.negative_points)&&finite(data.positive_points))points.push({label:'Le bilan du calcul',text:`${data.negative_points} points défavorables, compensés par ${data.positive_points} points favorables.`,tone:'neutral'});
out.note='Détail du calcul renseigné par Open Food Facts'+(p.nutriscore_version?' · version '+p.nutriscore_version:'')+'.';}
if(!points.length){for(const [id,label,help]of [['sugars_100g','Sucres','Les sucres entrent dans les points défavorables.'],['saturated-fat_100g','Graisses saturées','Elles entrent dans les points défavorables.'],['fiber_100g','Fibres','Elles peuvent apporter des points favorables.'],['salt_100g','Sel','Le sel entre dans les points défavorables.']]){if(finite(n[id])&&points.length<3)points.push({label,text:`${number(n[id])} g pour 100 g / 100 ml. ${help}`,tone:'neutral'});}out.note='Le détail du calcul n’est pas fourni. Ces valeurs sont des repères, pas une reconstitution de la note.';}}
if(m==='nova'){points.push({label:'Groupe '+p.nova_group,text:NOVA_TEXT[p.nova_group]+'. NOVA décrit le degré et le but de la transformation.',tone:'neutral'});const map={'en:whey':'lactosérum','en:sugar':'sucre','en:milk-powder':'lait en poudre','en:flavouring':'arôme','en:maltodextrin':'maltodextrine','en:glucose-syrup':'sirop de glucose','en:e322':'lécithines (E322)','en:modified-starch':'amidon modifié'};const markers=p.nova_groups_markers?.[String(p.nova_group)]||[];if(Array.isArray(markers)&&markers.length)points.push({label:'Marqueurs repérés par OFF',text:markers.slice(0,3).map(x=>{const id=Array.isArray(x)?x[1]:'';return map[id]||String(id).replace(/^\w\w:/,'').replaceAll('-',' ');}).filter(Boolean).join(' · ')+'.',tone:'warm'});const ingredients=p.ingredients_text_fr||p.ingredients_text;if(ingredients)points.push({label:'Dans la liste d’ingrédients',text:ingredients.replaceAll('_','').slice(0,190)+(ingredients.length>190?'…':''),tone:'neutral'});if(points.length===1)points.push({label:'Un autre regard',text:'Ce groupe ne mesure ni la qualité nutritionnelle ni l’impact environnemental.',tone:'neutral'});out.note=markers.length?'Classification et marqueurs renseignés par Open Food Facts.':'OFF fournit ce groupe, sans ses marqueurs détaillés pour cette fiche.';}
if(m==='eco'){const e=p.ecoscore_data||{};if(e.grade===p.ecoscore_grade){out.title='Ce qui compose cette note';if(finite(e.agribalyse?.score))points.push({label:'Base environnementale',text:`${number(e.agribalyse.score)} / 100 avant les ajustements${e.agribalyse.name_fr?' · catégorie « '+e.agribalyse.name_fr+' »':''}.`,tone:'neutral'});const adj=e.adjustments||{};for(const [key,label]of [['packaging','Emballage'],['production_system','Mode de production'],['origins_of_ingredients','Origine des ingrédients'],['threatened_species','Biodiversité']]){const v=adj[key]?.value;if(finite(v)&&v!==0&&points.length<3)points.push({label,text:`${v>0?'+':''}${number(v)} points dans le calcul OFF${adj[key].warning?' · des informations sont manquantes ou estimées':''}.`,tone:v>0?'good':'warm'});}if(points.length<3&&finite(e.score))points.push({label:'Score renseigné',text:`${number(e.score)} / 100 après les ajustements.`,tone:'neutral'});out.note='Détail environnemental fourni par Open Food Facts; certaines données peuvent être estimées.';}
if(!points.length){points.push({label:'Impact environnemental',text:`La fiche indique ${String(p.ecoscore_grade).toUpperCase()} sur l’échelle A à E.`,tone:'neutral'},{label:'Ce que l’indicateur évalue',text:'Le cycle de vie du produit, avec des ajustements liés notamment aux origines, à la production et aux emballages.',tone:'neutral'});out.note='Le détail du calcul est absent de cette fiche. Nous ne déduisons pas de cause particulière à cette lettre.';}}
return out;}
async function body(request){if(Number(request.headers.get('content-length')||0)>4096)fail('Requête trop volumineuse.',413);const text=await request.text();if(text.length>4096)fail('Requête trop volumineuse.',413);try{return JSON.parse(text);}catch{fail('Requête invalide.');}}
async function api(request,env){const url=new URL(request.url);if(!['GET','POST'].includes(request.method))fail('Méthode invalide.',405);if(request.method==='POST'&&(request.headers.get('origin')&&request.headers.get('origin')!==url.origin))fail('Origine refusée.',403);
const raw=request.headers.get('Authorization')?.replace(/^Bearer /,'')||'';if(!/^[a-f0-9]{64}$/.test(raw))fail('Profil absent. Recharge la page.',401);const token=await hash(raw);
if(url.pathname==='/api/rooms'&&request.method==='POST'){const b=await body(request),who=profile(b),opts=options(b);if(!/^[a-f0-9]{32}$/.test(b.operation||''))fail('Identifiant de création invalide.');const me={id:rid(),token,...who,score:0,base:0,vote:null,award:0,ready:false,stats:freshStats()},id=(await hash(token+b.operation)).slice(0,32);const s={id,phase:'lobby',gameId:rid(),step:rid(),host:me.id,players:[me],...opts,round:0,deck:[],history:[],createdAt:Date.now()};s.schedule=schedule(s);await db(env).prepare('INSERT OR IGNORE INTO rooms(id,state,version,updated_at) VALUES(?,?,0,?)').bind(id,JSON.stringify(s),Date.now()).run();return json(project((await read(env,id)).s,token));}
const match=url.pathname.match(/^\/api\/rooms\/([a-f0-9]{32})(?:\/(join|profile|settings|start|vote|ready|next|skip|lobby|leave))?$/);if(!match)fail('Route introuvable.',404);const [,id,action]=match;
if(request.method==='GET'&&!action){let {s}=await read(env,id);const before=JSON.stringify([s.phase,s.round,s.step]);advance(s,Date.now());if(JSON.stringify([s.phase,s.round,s.step])!==before)s=await mutate(env,id,()=>{});return json(project(s,token));}
if(request.method!=='POST'||!action)fail('Route introuvable.',404);const b=await body(request);
if(action==='start'){const job=rid();await mutate(env,id,s=>{host(s,token);if(s.phase!=='lobby')fail('La partie est déjà démarrée.',409);if(s.players.length<2)fail('Il faut au moins deux joueurs.');s.phase='loading';s.loadingAt=Date.now();s.loadingJob=job;s.error=null;});try{const {s}=await read(env,id);const drawn=await draw(env,s);const next=await mutate(env,id,r=>{if(r.phase!=='loading'||r.loadingJob!==job)fail('Le tirage a expiré. Réessaie.',409);r.deck=drawn.deck;r.source=drawn.source;r.schedule=schedule(r);r.round=0;r.history=[];r.gameId=rid();r.deadline=null;r.lockAt=null;r.landAt=null;r.resultAt=null;r.players.forEach(p=>{p.score=0;p.base=0;p.vote=null;p.award=0;p.stats=freshStats();});newGate(r,'intro',Date.now());});return json(project(next,token));}catch(e){await mutate(env,id,s=>{if(s.phase==='loading'&&s.loadingJob===job){s.phase='lobby';s.error=e.status?e.message:'Le tirage a échoué. Réessaie.';}});throw e;}}
const s=await mutate(env,id,s=>{
if(action==='join'){if(s.players.find(p=>p.token===token))return;if(s.phase!=='lobby')fail('La partie a commencé. Attends le retour au salon.',409);if(s.players.length>=8)fail('Le salon est complet (8 joueurs).');s.players.push({id:rid(),token,...profile(b),score:0,base:0,vote:null,award:0,ready:false,stats:freshStats()});return;}
const me=member(s,token);
if(action==='profile'){if(s.phase!=='lobby')fail('Les profils sont fixés pendant la partie.',409);Object.assign(me,profile(b));}
if(action==='settings'){host(s,token);if(s.phase!=='lobby')fail('La partie est déjà démarrée.',409);Object.assign(s,options(b));s.schedule=schedule(s);}
if(action==='vote'){if(s.phase!=='vote'||b.round!==s.round+1||(s.gameId!=='legacy'&&b.gameId!==s.gameId))fail('Les votes sont verrouillés.',409);if(!choices(mode(s)).includes(b.choice))fail('Vote invalide.');me.vote=b.choice;if(!s.deadline)s.deadline=Date.now()+s.seconds*1000;if(s.players.every(p=>p.vote))lock(s,Date.now());}
if(action==='ready'){if(!['intro','results'].includes(s.phase)||b.step!==s.step||b.gameId!==s.gameId)fail('Cette étape est déjà terminée.',409);me.ready=b.ready!==false;advance(s,Date.now());}
if(action==='next')fail('Chaque joueur doit maintenant utiliser « Prêt ». Recharge la page pour la nouvelle version.',409);
if(action==='skip'){host(s,token);if(s.phase!=='vote'||b.round!==s.round+1||(s.gameId!=='legacy'&&b.gameId!==s.gameId))fail('La manche est déjà verrouillée.',409);s.skipped=true;s.players.forEach(p=>p.vote=null);lock(s,Date.now());}
if(action==='lobby'){host(s,token);if(s.phase!=='finished')fail('La partie est encore en cours.',409);s.lastFinal??=snapshot(s);s.phase='lobby';s.step=rid();s.deck=[];s.round=0;s.deadline=null;s.lockAt=null;s.readyDeadline=null;s.players.forEach(p=>p.ready=false);}
if(action==='leave'){if(!['finished','lobby'].includes(s.phase))fail('Tu peux quitter après la partie. Fermer le navigateur conserve ta place.',409);if(s.phase==='finished')s.lastFinal??=snapshot(s);s.players=s.players.filter(p=>p.id!==me.id);if(s.host===me.id)s.host=s.players[0]?.id||null;}
});return json(project(s,token));}
export default {async fetch(request,env,ctx){try{const url=new URL(request.url);if(url.pathname.startsWith('/api/'))return await api(request,env);const path=url.pathname==='/'?'/index.html':url.pathname;const f=STATIC_FILES[path];if(!f)return new Response('Introuvable',{status:404});if(!['GET','HEAD'].includes(request.method))return new Response('Méthode invalide',{status:405});return new Response(request.method==='HEAD'?null:Uint8Array.from(atob(f.data),c=>c.charCodeAt(0)),{headers:{'Content-Type':f.type,'Cache-Control':/\.html$|\.js$|\.css$/.test(path)?'no-cache':'public, max-age=3600','X-Content-Type-Options':'nosniff','Referrer-Policy':'same-origin'}});}catch(e){if(!e.status)console.error('NutriDeck API',e.message);return json({error:e.status?e.message:'Connexion interrompue. Ta partie est conservée; réessaie.'},e.status||503);}}};
