// Server-authoritative rooms. CAS on each room makes votes, locking and scoring atomic.
const AVATARS=['😀','🦊','🐼','🐸','🦁','🐙','🐵','🐯','🐨','🐧','🦄','🐻','🐮','🐷','🐹','🐰','🤖','🧓','🧢'];
const GRADES='ABCDE';
const json=(v,status=200)=>Response.json(v,{status,headers:{'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});
function fail(message,status=400){throw Object.assign(new Error(message),{status});}
const db=env=>{if(!env.DB)fail('Le salon est temporairement indisponible.',503);return env.DB;};
const hash=async s=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s))),x=>x.toString(16).padStart(2,'0')).join('');
const rid=()=>crypto.randomUUID().replaceAll('-','');
function profile(b){const name=String(b.name||'').trim().replace(/[\x00-\x1f]/g,'').slice(0,24);if(!name)fail('Choisis ton nom.');if(!AVATARS.includes(b.avatar))fail('Choisis un avatar.');return{name,avatar:b.avatar};}
function options(b){const count=Number(b.count),seconds=Number(b.seconds);if(!Number.isInteger(count)||count<1||count>20||![12,20,30,45].includes(seconds))fail('Réglages invalides.');return{count,seconds};}
async function read(env,id){const r=await db(env).prepare('SELECT state,version FROM rooms WHERE id=?').bind(id).first();if(!r)fail('Ce salon est introuvable. Vérifie le lien.',404);return{s:JSON.parse(r.state),version:r.version};}
function lock(s,now){s.phase='reveal';s.lockAt=now;s.deadline=null;const answer=s.deck[s.round].nutriscore_grade.toUpperCase();for(const p of s.players){p.base=p.score;p.award=p.vote==null?0:([1000,600,250][Math.abs(GRADES.indexOf(p.vote)-GRADES.indexOf(answer))]||0);p.score+=p.award;}}
function advance(s,now){if(s.phase==='vote'&&s.deadline&&now>=s.deadline)lock(s,s.deadline);if(s.phase==='reveal'&&now>=s.lockAt+6000)s.phase=s.round+1>=s.count?'finished':'results';if(s.phase==='loading'&&now-s.loadingAt>90000){s.phase='lobby';s.error='Le chargement a été interrompu. Tu peux réessayer.';}}
async function mutate(env,id,fn){for(let i=0;i<12;i++){const {s,version}=await read(env,id);advance(s,Date.now());await fn(s);const r=await db(env).prepare('UPDATE rooms SET state=?,version=version+1,updated_at=? WHERE id=? AND version=?').bind(JSON.stringify(s),Date.now(),id,version).run();if(r.meta.changes)return s;}fail('La table se synchronise. Réessaie.',409);}
function member(s,token){const p=s.players.find(p=>p.token===token);if(!p)fail('Rejoins le salon avec ton profil.',401);return p;}
function host(s,token){const p=member(s,token);if(p.id!==s.host)fail('Seul l’hôte peut faire cette action.',403);return p;}
function project(s,token){const me=s.players.find(p=>p.token===token);const now=Date.now(),landed=['results','finished'].includes(s.phase)||(s.phase==='reveal'&&now>=s.lockAt+4300),locked=['reveal','results','finished'].includes(s.phase);let product=null;
if(me&&s.deck?.[s.round]){product=structuredClone(s.deck[s.round]);if(!landed){delete product.nutriscore_grade;delete product.nova_group;delete product.ecoscore_grade;}}
return{id:s.id,phase:s.phase,host:s.host,me:me?.id||null,count:s.count,seconds:s.seconds,round:s.round+1,serverNow:now,deadline:s.deadline||null,lockAt:s.lockAt||null,landed,error:s.error||null,source:s.source||null,revealTarget:me&&locked?s.deck[s.round].nutriscore_grade.toUpperCase():null,product,players:s.players.map(p=>({id:p.id,name:p.name,avatar:p.avatar,score:landed?p.score:(p.base??p.score),base:p.base??p.score,award:landed?p.award||0:0,voted:!!p.vote,vote:me&&(locked||p.id===me.id)?p.vote:null,host:p.id===s.host}))};}
const fields=['code','product_name','product_name_fr','brands','quantity','image_front_url','nutriscore_grade','nutrition_grades','nova_group','nova_groups','ecoscore_grade','nutriments','ingredients_text','ingredients_text_fr','allergens_tags','traces_tags','additives_tags','additives_n'];
function normalized(p){const o={};for(const k of fields)if(p[k]!=null)o[k]=p[k];o.code=String(o.code||'');o.brands=Array.isArray(o.brands)?o.brands.join(', '):o.brands||'';o.nutriscore_grade=String(o.nutriscore_grade||o.nutrition_grades||'').toLowerCase();o.nova_group=Number(o.nova_group||o.nova_groups)||null;delete o.nutrition_grades;delete o.nova_groups;return o;}
function eligible(p){return /^\d{4,24}$/.test(p.code)&&/^[a-e]$/.test(p.nutriscore_grade)&&!!(p.product_name_fr||p.product_name)&&/^https:\/\/images\.openfoodfacts\.org\//.test(p.image_front_url||'')&&['energy-kcal_100g','energy-kj_100g','sugars_100g','salt_100g','saturated-fat_100g','proteins_100g'].filter(k=>Number.isFinite(p.nutriments?.[k])).length>=4;}
const shuffle=a=>{for(let i=a.length-1;i>0;i--){const bytes=new Uint32Array(1);crypto.getRandomValues(bytes);const j=bytes[0]%(i+1);[a[i],a[j]]=[a[j],a[i]];}return a;};
async function offJSON(url,timeout=12000){const r=await fetch(url,{headers:{'User-Agent':'NutriDeckGym/0.6 (https://github.com/jutrasimon/nutrideck)','Accept':'application/json'},signal:AbortSignal.timeout(timeout)});if(!r.ok||!r.headers.get('content-type')?.includes('json'))throw Error('OFF unavailable');return r.json();}
async function draw(env,count){
const page=1+Math.floor(Math.random()*90),key='off-page-'+page,now=Date.now();const cached=await db(env).prepare('SELECT payload FROM off_cache WHERE id=? AND expires_at>?').bind(key,now).first();let pool,source='Open Food Facts';
if(cached)pool=JSON.parse(cached.payload);else{
// One shared lease limits expensive OFF searches across every room (max ~8/min).
const lease=await db(env).prepare('INSERT INTO off_cache(id,payload,expires_at) VALUES(?,?,?) ON CONFLICT(id) DO UPDATE SET expires_at=excluded.expires_at WHERE off_cache.expires_at<?').bind('search-lease','{}',now+8000,now).run();if(!lease.meta.changes)fail('Un tirage est déjà en cours. Réessaie dans quelques secondes.',429);
try{const u=new URL('https://world.openfoodfacts.org/api/v2/search');u.search=new URLSearchParams({page:String(page),page_size:'100',sort_by:'unique_scans_n',fields:fields.join(',')});const data=await offJSON(u,10000);pool=(data.products||[]).map(normalized).filter(eligible);}catch{pool=[];}
if(pool.length<count){const u=new URL('https://search.openfoodfacts.org/search');u.search=new URLSearchParams({q:'nutriscore_grade:(a OR b OR c OR d OR e)',page:String(page),page_size:'100',langs:'fr,en',fields:fields.join(',')});try{const data=await offJSON(u,20000);pool=(data.hits||[]).map(normalized).filter(eligible);source='Open Food Facts · index de recherche';}catch{fail('Open Food Facts ne répond pas pour le moment. Le salon est conservé; réessaie le tirage.',503);}}
if(pool.length<count)fail('Pas assez de fiches complètes dans ce tirage. Réessaie pour obtenir un autre lot.',503);
await db(env).prepare('INSERT INTO off_cache(id,payload,expires_at) VALUES(?,?,?) ON CONFLICT(id) DO UPDATE SET payload=excluded.payload,expires_at=excluded.expires_at').bind(key,JSON.stringify(pool),now+3600000).run();}
const deck=shuffle([...new Map(pool.map(p=>[p.code,p])).values()]).slice(0,count);if(deck.length<count)fail('Tirage incomplet. Réessaie.',503);
// Search index can omit ingredients; hydrate through the product API when reachable.
let cursor=0;await Promise.all(Array.from({length:Math.min(4,count)},async()=>{while(cursor<deck.length){const i=cursor++,p=deck[i];if(p.ingredients_text||p.ingredients_text_fr)continue;try{const d=await offJSON('https://world.openfoodfacts.org/api/v2/product/'+p.code+'.json?fields='+fields.join(','),4500);if(d.product){const fresh=normalized(d.product);if(eligible(fresh))deck[i]=fresh;}}catch{}}}));
return{deck,source};}
async function body(request){if(Number(request.headers.get('content-length')||0)>4096)fail('Requête trop volumineuse.',413);const text=await request.text();if(text.length>4096)fail('Requête trop volumineuse.',413);try{return JSON.parse(text);}catch{fail('Requête invalide.');}}
async function api(request,env){const url=new URL(request.url);if(!['GET','POST'].includes(request.method))fail('Méthode invalide.',405);if(request.method==='POST'&&(request.headers.get('origin')&&request.headers.get('origin')!==url.origin))fail('Origine refusée.',403);
const raw=request.headers.get('Authorization')?.replace(/^Bearer /,'')||'';if(!/^[a-f0-9]{64}$/.test(raw))fail('Profil absent. Recharge la page.',401);const token=await hash(raw);
if(url.pathname==='/api/rooms'&&request.method==='POST'){const b=await body(request),who=profile(b),opts=options(b);const me={id:rid(),token,...who,score:0,base:0,vote:null,award:0},id=rid();const s={id,phase:'lobby',host:me.id,players:[me],...opts,round:0,deck:[],createdAt:Date.now()};
// Retries with the same client operation ID resume the same room.
if(!/^[a-f0-9]{32}$/.test(b.operation||''))fail('Identifiant de création invalide.');const roomId=(await hash(token+b.operation)).slice(0,32);s.id=roomId;
await db(env).prepare('INSERT OR IGNORE INTO rooms(id,state,version,updated_at) VALUES(?,?,0,?)').bind(roomId,JSON.stringify(s),Date.now()).run();return json(project((await read(env,roomId)).s,token));}
const match=url.pathname.match(/^\/api\/rooms\/([a-f0-9]{32})(?:\/(join|profile|settings|start|vote|next|skip|lobby))?$/);if(!match)fail('Route introuvable.',404);const [,id,action]=match;
if(request.method==='GET'&&!action){let {s}=await read(env,id);const old=s.phase;advance(s,Date.now());if(s.phase!==old)s=await mutate(env,id,()=>{});return json(project(s,token));}
if(request.method!=='POST'||!action)fail('Route introuvable.',404);const b=await body(request);
if(action==='start'){
const job=rid();let started=false;await mutate(env,id,s=>{host(s,token);if(s.phase!=='lobby')fail('La partie est déjà démarrée.',409);if(s.players.length<2)fail('Il faut au moins deux joueurs.');s.phase='loading';s.loadingAt=Date.now();s.loadingJob=job;s.error=null;started=true;});
try{const {s}=await read(env,id);const drawn=await draw(env,s.count);const next=await mutate(env,id,r=>{if(r.phase!=='loading'||r.loadingJob!==job)fail('Le tirage a expiré. Réessaie.',409);r.deck=drawn.deck;r.source=drawn.source;r.round=0;r.phase='vote';r.deadline=null;r.lockAt=null;r.players.forEach(p=>{p.score=0;p.base=0;p.vote=null;p.award=0;});});return json(project(next,token));}
catch(e){if(started)await mutate(env,id,s=>{if(s.phase==='loading'&&s.loadingJob===job){s.phase='lobby';s.error=e.status?e.message:'Le tirage a échoué. Réessaie.';}});throw e;}}
const s=await mutate(env,id,s=>{
if(action==='join'){let p=s.players.find(p=>p.token===token);if(p)return;if(s.phase!=='lobby')fail('La partie a commencé. Attends le retour au salon.',409);if(s.players.length>=8)fail('Le salon est complet (8 joueurs).');s.players.push({id:rid(),token,...profile(b),score:0,base:0,vote:null,award:0});return;}
const me=member(s,token);
if(action==='profile'){if(s.phase!=='lobby')fail('Les profils sont fixés pendant la partie.',409);Object.assign(me,profile(b));}
if(action==='settings'){host(s,token);if(s.phase!=='lobby')fail('La partie est déjà démarrée.',409);Object.assign(s,options(b));}
if(action==='vote'){if(s.phase!=='vote'||b.round!==s.round+1)fail('Les votes sont verrouillés.',409);if(!/^[A-E]$/.test(b.choice||''))fail('Vote invalide.');me.vote=b.choice;if(!s.deadline)s.deadline=Date.now()+s.seconds*1000;if(s.players.every(p=>p.vote))lock(s,Date.now());}
if(action==='next'){host(s,token);if(s.phase!=='results'||b.round!==s.round+1)fail('Cette manche est déjà terminée ou le reveal est en cours.',409);s.round++;s.phase='vote';s.deadline=null;s.lockAt=null;s.players.forEach(p=>{p.base=p.score;p.vote=null;p.award=0;});}
if(action==='skip'){host(s,token);if(s.phase!=='vote'||b.round!==s.round+1)fail('La manche est déjà verrouillée.',409);s.players.forEach(p=>p.vote=null);lock(s,Date.now());}
if(action==='lobby'){host(s,token);if(s.phase!=='finished')fail('La partie est encore en cours.',409);s.phase='lobby';s.deck=[];s.round=0;s.deadline=null;s.lockAt=null;s.players.forEach(p=>{p.score=0;p.base=0;p.vote=null;p.award=0;});}
});return json(project(s,token));}
export default {async fetch(request,env,ctx){try{const url=new URL(request.url);if(url.pathname.startsWith('/api/'))return await api(request,env);const path=url.pathname==='/'?'/index.html':url.pathname;const f=STATIC_FILES[path];if(!f)return new Response('Introuvable',{status:404});if(!['GET','HEAD'].includes(request.method))return new Response('Méthode invalide',{status:405});return new Response(request.method==='HEAD'?null:Uint8Array.from(atob(f.data),c=>c.charCodeAt(0)),{headers:{'Content-Type':f.type,'Cache-Control':/\.html$|\.js$|\.css$/.test(path)?'no-cache':'public, max-age=3600','X-Content-Type-Options':'nosniff','Referrer-Policy':'same-origin'}});}catch(e){if(!e.status)console.error('NutriDeck API',e.message);return json({error:e.status?e.message:'Connexion interrompue. Ta partie est conservée; réessaie.'},e.status||503);}}};
