import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import assert from 'node:assert/strict';
import worker from '../dist/server/index.js';
const sqlite=new DatabaseSync(':memory:');sqlite.exec(readFileSync('drizzle/0000_deep_wraith.sql','utf8'));
const DB={prepare(sql){return {bind(...params){return{async first(){return sqlite.prepare(sql).get(...params)||null},async run(){const r=sqlite.prepare(sql).run(...params);return{meta:{changes:r.changes}}}}}}}};
const tokens=['a'.repeat(64),'b'.repeat(64),'c'.repeat(64),'d'.repeat(64)];
let clock=Date.now();Date.now=()=>clock;
async function req(path,who=0,data,status=200){const r=await worker.fetch(new Request('https://nutri.test/api/rooms'+path,{method:data===undefined?'GET':'POST',headers:{Authorization:'Bearer '+tokens[who],'Content-Type':'application/json'},body:data===undefined?undefined:JSON.stringify(data)}),{DB},{});const d=await r.json();assert.equal(r.status,status,JSON.stringify(d));return d;}
const body={name:'Simon',avatar:'🦊',count:2,seconds:20,operation:'f'.repeat(32)};
const room=await req('',0,body),id=room.id;
assert.equal((await req('',0,body)).id,id,'create idempotent');
await Promise.all([req('/'+id+'/join',1,{name:'Paul',avatar:'🐼'}),req('/'+id+'/join',2,{name:'Kattie',avatar:'🐸'})]);
let snap=await req('/'+id);assert.equal(snap.players.length,3,'concurrent joins preserved');
await req('/'+id+'/start',1,{},403);
const fixture=JSON.parse(readFileSync('public/gym-products.json'));fixture.forEach(p=>{delete p.localImage;p.image_front_url='https://images.openfoodfacts.org/test.jpg';p.ingredients_text='Ingrédients de test';});
globalThis.fetch=async()=>Response.json({products:fixture});
snap=await req('/'+id+'/start',0,{});assert.equal(snap.phase,'vote');assert(!('nutriscore_grade' in snap.product),'answer never sent before reveal');assert(snap.product.nutriments.sugars_100g!=null);
await req('/'+id+'/vote',0,{choice:'A',round:1});snap=await req('/'+id+'/vote',0,{choice:'B',round:1});assert.equal(snap.players[0].vote,'B','can change vote');assert(snap.deadline>clock);
snap=await req('/'+id,1);assert.equal(snap.players[0].vote,null,'other votes hidden');
const saved=JSON.parse(sqlite.prepare('SELECT state FROM rooms WHERE id=?').get(id).state),correct=saved.deck[0].nutriscore_grade.toUpperCase();
await Promise.all([req('/'+id+'/vote',1,{choice:correct,round:1}),req('/'+id+'/vote',2,{choice:correct,round:1})]);
snap=await req('/'+id);assert.equal(snap.phase,'reveal');assert.equal(snap.players[0].vote,'B');assert(!snap.product.nutriscore_grade);await req('/'+id+'/vote',0,{choice:'D',round:1},409);
clock+=4400;snap=await req('/'+id);assert.equal(snap.product.nutriscore_grade.toUpperCase(),correct);assert.equal(snap.players[1].award,1000);const totals=snap.players.map(p=>p.score);
clock+=2000;await Promise.all(Array.from({length:8},()=>req('/'+id)));snap=await req('/'+id);assert.equal(snap.phase,'results');assert.deepEqual(snap.players.map(p=>p.score),totals,'no duplicate scoring under concurrent polling');
await req('/'+id+'/next',1,{round:1},403);await req('/'+id+'/next',0,{round:1});await req('/'+id+'/next',0,{round:1},409);
await req('/'+id+'/vote',0,{choice:'A',round:1},409);await req('/'+id+'/vote',0,{choice:'A',round:2});
clock+=25000;snap=await req('/'+id,0);assert.equal(snap.phase,'reveal','deadline advances while all browsers closed');clock+=6100;snap=await req('/'+id);assert.equal(snap.phase,'finished');assert.equal(snap.players[1].award,0);assert.equal(snap.players[1].score,totals[1]);assert.equal(snap.me,room.me,'same token resumes same player');
await req('/'+id+'/join',3,{name:'Late',avatar:'😀'},409);await req('/'+id+'/lobby',0,{});assert.equal((await req('/'+id)).players.length,3,'replay preserves profiles');
console.log('PASS atomic joins/votes, idempotent create, secret answers, vote changes, lock, timers offline, exact scoring, host permissions, replay/resume.');
